let attendanceDayTimer;
async function attendancePage(){
 clearTimeout(attendanceDayTimer);
 const manager=current==='attendanceadmin';if(manager&&session.user.role!=='SUPER ADMIN')throw Error('Akses ditolak.');
 const range=filters.attendance||{from:today().slice(0,7)+'-01',to:today()},query=new URLSearchParams(range),time=v=>v?new Date(v).toLocaleString('id-ID',{timeZone:'Asia/Jakarta',hour12:false})+' WIB':'—',duration=v=>v===null||v===undefined?'—':Math.floor(v/60)+' jam '+v%60+' menit';
 const days=['Senin','Selasa','Rabu','Kamis','Jumat','Sabtu','Minggu'];
 const describe=s=>s.week?s.week.map((d,i)=>days[i]+': '+(d.off?'Libur':d.start+'–'+d.end)).join(' · '):s.start+'–'+s.end;
 const data=manager?await api('/api/attendance/settings'):await api('/api/attendance?'+query),rows=manager?await api('/api/attendance/recap?'+query):data.rows;
 $('#content').innerHTML=header(manager?'<a class="secondary" href="/api/attendance/export?'+esc(query.toString())+'">Unduh Excel</a>':'')+(manager?'<p>Jadwal Senin–Minggu per username, dalam WIB. Pilih Masuk atau Libur setiap hari. Perubahan berlaku mulai tanggal yang dipilih; riwayat sebelumnya tetap. Jam pulang lebih kecil berarti pulang keesokan hari.</p><section class="card panel"><h3>Jadwal pengguna</h3>'+financeTable(['Nama / username','Jadwal','Status','Aksi'],data.users.map(u=>{const s=data.schedules.find(s=>s.userId===u.id);return [esc(u.name)+' / '+esc(u.username),s?esc(describe(s))+'<br>Mulai '+esc(s.effectiveFrom||s.createdDate):'Belum diatur',s?.enabled?'Aktif':'Belum aktif','<button class="link" data-schedule="'+esc(u.id)+'">Atur jadwal</button>'];}))+'</section>':'<section class="card panel"><h3>'+esc(session.user.name)+' · '+esc(session.user.username)+'</h3><p>Tanggal absen (otomatis, WIB): <strong>'+esc(data.today)+'</strong></p><p>Jadwal: '+(data.schedule?.enabled?(data.schedule.off?'Libur':esc(data.schedule.start+'–'+data.schedule.end)+' WIB'):'Belum aktif; hubungi Super Admin')+'</p><p>Waktu dicatat otomatis dari server. '+(data.completedToday?'Absensi hari ini selesai. Tombol kembali tersedia besok sesuai jadwal.':data.open?'Absen masuk terbuka sejak '+esc(time(data.open.inAt)): 'Belum ada sesi kerja terbuka.')+'</p><button class="primary" id="attendanceIn" '+(data.completedToday||!data.schedule?.enabled||data.schedule?.off||data.open?'disabled':'')+'>Absen Masuk</button> <button class="primary" id="attendanceOut" '+(data.completedToday||!data.open?'disabled':'')+'>Absen Pulang</button></section>')+
 '<h3>Riwayat absensi</h3><p>Pilihan tanggal berikut hanya menyaring riwayat, bukan tanggal untuk absen.</p><form id="attendanceFilter" class="filter-bar">'+field('from','Dari tanggal','date',range.from)+field('to','Sampai tanggal','date',range.to)+(manager?field('userId','Username','select',range.userId||'',data.users.map(u=>({id:u.id,name:u.username+' — '+u.name})),false):'')+'<button class="primary">Tampilkan</button></form><p>Durasi adalah selisih masuk–pulang, belum dikurangi istirahat. Lewat jadwal bukan otomatis lembur disetujui. Tanggal riwayat mengikuti tanggal masuk.</p>'+financeTable(['Tanggal','Nama / username','Status','Jadwal WIB','Masuk','Pulang','Durasi','Terlambat','Pulang awal','Lewat jadwal','Lembur disetujui',...(manager?['Aksi']:[])],rows.map(r=>[esc(r.date),esc(r.name)+' / '+esc(r.username),esc(r.status),r.scheduleStart?esc(r.scheduleStart+'–'+r.scheduleEnd):'—',esc(time(r.inAt)),esc(time(r.outAt)),duration(r.duration),duration(r.late),duration(r.early),duration(r.extra),duration(r.overtimeMinutes)+(r.overtimeNote?'<br>'+esc(r.overtimeNote):''),...(manager?[r.outAt?'<button class="link" data-overtime="'+esc(r.id)+'">Tinjau lembur</button>':r.virtual?'—':'Belum absen pulang']:[])]));
 $('#attendanceFilter').onsubmit=safe(async e=>{e.preventDefault();filters.attendance=formData(e.target);await attendancePage();});
 if(!manager){
  const resetAt=Date.parse(data.today+'T00:00:00+07:00')+86400000;
  attendanceDayTimer=setTimeout(()=>{if(current==='attendance'&&session?.user)safe(async()=>attendancePage())();},Math.max(1000,resetAt-Date.parse(data.serverNow)+1000));
  let saving=false;
  for(const [id,action]of [['attendanceIn','in'],['attendanceOut','out']])$('#'+id).onclick=safe(async()=>{
   const button=$('#'+id);if(saving||button.disabled)return;saving=true;button.disabled=true;
   try{await api('/api/attendance/punch',{method:'POST',body:{action}});toast(action==='in'?'Absen masuk tercatat.':'Absen pulang tercatat.');}
   finally{try{await attendancePage();}finally{saving=false;}}
  });return;
 }
 $$('[data-schedule]').forEach(b=>b.onclick=()=>{const u=data.users.find(u=>u.id===b.dataset.schedule),s=data.schedules.find(s=>s.userId===u.id)||{},week=s.week||days.map(()=>({off:false,start:s.start||'08:00',end:s.end||'17:00'}));modal('Jadwal '+u.username,'<p>Atur jadwal mingguan. Jam di hari Libur diabaikan. Jadwal yang sudah dipakai untuk absen tetap tersimpan.</p>'+field('effectiveFrom','Berlaku mulai tanggal','date',s.effectiveFrom>today()?s.effectiveFrom:today())+field('enabled','Aktifkan absensi','checkbox',s.enabled??true)+days.map((name,i)=>'<fieldset><legend>'+name+'</legend>'+field('day'+i,'Status','select',week[i].off?'Libur':'Masuk',['Masuk','Libur'])+field('start'+i,'Jam masuk (WIB)','time',week[i].start||'08:00',[],false)+field('end'+i,'Jam pulang (WIB)','time',week[i].end||'17:00',[],false)+'</fieldset>').join(''),async d=>api('/api/attendance/settings',{method:'POST',body:{userId:u.id,enabled:d.enabled,effectiveFrom:d.effectiveFrom,week:days.map((_,i)=>({off:d['day'+i]==='Libur',start:d['start'+i],end:d['end'+i]}))}}),{wide:true});});
 $$('[data-overtime]').forEach(b=>b.onclick=()=>{const r=rows.find(r=>r.id===b.dataset.overtime);modal('Tinjau lembur — '+r.username,'<p>Lewat jadwal: '+duration(r.extra)+'.</p>'+field('minutes','Menit lembur disetujui (0 jika tidak)','number',r.overtimeMinutes??0)+field('notes','Catatan','textarea',r.overtimeNote||'',[],false),async d=>api('/api/attendance/overtime',{method:'POST',body:{...d,id:r.id}}));});
}
