/* Batch editing reuses the same domain validation as individual editors. */
function bulkEditButton(records,mode='edit'){
 const available=records.filter(r=>can(r.kind==='posproducts'?'posmaster':r.kind==='posorders'?'pos':r.kind,'edit')&&!r.legacy&&!r.posDayId);
 if(!available.length)return;
 const bar=$('#content .welcome .button-row');if(!bar)return;
 const button=document.createElement('button');button.type='button';button.className='secondary';button.textContent=mode==='stock'?'Atur Stok Massal':'Edit Massal';bar.append(button);
 button.onclick=()=>bulkChoose(available,mode);
}
function bulkChoose(records,mode){
 const selected=new Set();
 modal(mode==='stock'?'Pilih produk untuk Atur Stok Massal':'Pilih data untuk Edit Massal','<p>Pilih maksimal 100 data. Daftar mengikuti filter menu yang sedang dibuka.</p><label>Cari<input id="bulkSearch" placeholder="Nama, nomor, atau keterangan"></label><div class="button-row"><button type="button" id="bulkSelect" class="secondary">Pilih hasil pencarian</button><button type="button" id="bulkClear" class="secondary">Kosongkan pilihan</button></div><p id="bulkCount"></p><div id="bulkChoices" class="bulk-choice-list"></div><button type="button" id="bulkContinue" class="primary">Lanjutkan</button>',null,{wide:true});
 const label=r=>[r.name||r.number||r.username||r.id,r.date,r.description,r.category].filter(Boolean).join(' · ');
 const visible=()=>records.map((r,n)=>({r,n})).filter(({r})=>label(r).toLowerCase().includes($('#bulkSearch').value.toLowerCase()));
 const draw=()=>{const list=visible();$('#bulkCount').textContent=selected.size+' data dipilih';$('#bulkChoices').innerHTML=list.map(({r,n})=>'<label class="bulk-choice"><input type="checkbox" data-bulk-choice="'+n+'" '+(selected.has(n)?'checked':'')+'>'+esc(label(r))+'</label>').join('');$$('[data-bulk-choice]').forEach(el=>el.onchange=()=>{const n=Number(el.dataset.bulkChoice);if(el.checked&&selected.size>=100){el.checked=false;toast('Maksimal 100 data.');return;}el.checked?selected.add(n):selected.delete(n);$('#bulkCount').textContent=selected.size+' data dipilih';});};
 $('#bulkSearch').oninput=draw;$('#bulkSelect').onclick=()=>{for(const {n}of visible()){if(selected.size>=100)break;selected.add(n);}draw();};$('#bulkClear').onclick=()=>{selected.clear();draw();};
 $('#bulkContinue').onclick=safe(async()=>{if(!selected.size)throw Error('Pilih minimal satu data.');const rows=await api('/api/bulk-edit/read',{method:'POST',body:{rows:[...selected].map(n=>({kind:records[n].kind,id:records[n].id}))}});await bulkEditor(rows,mode);});draw();
}
async function bulkEditor(entries,mode){
 const stocks=mode==='stock'?await api('/api/pos/stock-options'):[],queueProducts=entries.some(r=>r.kind==='posorders')?await api('/api/pos/products'):[];
 const special={posproducts:[['name','Nama produk'],['category','Kategori'],['price','Harga jual','number'],['cost','HPP standar','number'],['active','Aktif','checkbox']],contacts:[['name','Nama'],['phone','WhatsApp'],['category','Kategori','text',false],['notes','Keterangan','textarea',false]],users:[['name','Nama'],['username','Username'],['password','Password baru (kosongkan jika tetap)','password',false],['role','Role',Object.keys(session.roles)],['active','Aktif','checkbox']],invoices:[['customerId','Customer','customers'],['unitId','Unit bisnis','units'],['date','Tanggal','date'],['dueDate','Jatuh tempo','date'],['bankId','Rekening','banks',false],['eventDate','Tanggal acara','date',false],['eventStart','Jam mulai','time',false],['eventEnd','Jam selesai','time',false],['discount','Diskon invoice','number'],['other','Biaya lainnya','number'],['notes','Catatan','textarea',false]],posorders:[['customerName','Nama customer','text',false],['phone','WhatsApp','tel',false],['discount','Diskon','number'],['discountReason','Alasan diskon','text',false],['notes','Catatan','textarea',false]]};
 const recipes=entries.map(r=>structuredClone(r.data.stockRecipe||[])),itemRows=entries.map(r=>structuredClone(r.data.items||[]));
 const defs=r=>mode==='stock'?[]:special[r.kind]||spec[r.kind]||[];
 const input=(def,value,prefix)=>{let [key,label,type='text',required=true]=def,list=[];if(Array.isArray(type)){list=type;type='select';}else if(lookups[type]){list=lookups[type];type='select';}if(type==='select'&&value&&!list.some(x=>String(typeof x==='object'?x.id:x)===String(value)))list=[...list,{id:value,name:'Tersimpan: '+value}];return field(prefix+key,label,type,value??'',list,required).replace('name="'+prefix+key+'"','data-bulk-field="'+key+'" name="'+prefix+key+'"');};
 modal(mode==='stock'?'Atur Stok Massal':'Edit Massal', '<p>'+entries.length+' data. Periksa setiap bagian sebelum Simpan Semua. Jika ada kesalahan, seluruh perubahan dibatalkan.</p>'+(mode==='stock'?'<p>Pemakaian per 1 produk. Berlaku untuk pesanan baru; kosong berarti tidak memakai stok.</p><button type="button" class="secondary" id="copyRecipe">Salin susunan produk pertama ke semua produk pilihan</button>':'')+entries.map((r,n)=>'<details class="bulk-edit-row" data-bulk-row="'+n+'" open><summary>'+esc((n+1)+'. '+(r.data.name||r.data.number||r.data.username||r.id))+'</summary><div class="form-grid">'+defs(r).map(d=>input(d,d[0]==='password'?'':d[2]==='checkbox'?!!r.data[d[0]]:r.data[d[0]],'be'+n+'_')).join('')+'</div><div class="bulk-nested"></div></details>').join(''),async(d,form)=>{
  const changes=[];for(const el of form.querySelectorAll('[data-bulk-row]')){const n=Number(el.dataset.bulkRow),r=entries[n],patch={};
   for(const control of el.querySelectorAll(':scope > .form-grid [data-bulk-field]')){if(control.disabled)continue;const key=control.dataset.bulkField;if(control.type==='file'){if(control.files[0])patch[key]=await fileValue(control.files[0]);continue;}const value=control.type==='checkbox'?control.checked:control.value;if(key==='password'&&!value)continue;const original=r.data[key]??'';if(String(value)!==String(control.type==='checkbox'?!!original:original))patch[key]=value;}
   if(mode==='stock'&&JSON.stringify(recipes[n])!==JSON.stringify(r.data.stockRecipe||[]))patch.stockRecipe=recipes[n];
   if(['invoices','posorders'].includes(r.kind)&&JSON.stringify(itemRows[n])!==JSON.stringify(r.data.items||[]))patch.items=itemRows[n];
   if(r.kind==='users'){const permissions=Object.fromEntries(session.modules.map(m=>[m,[...el.querySelectorAll('[data-permission]:checked')].filter(c=>c.dataset.permission===m).map(c=>c.value)]));if(JSON.stringify(permissions)!==JSON.stringify(r.data.permissions))patch.permissions=permissions;}
   if(Object.keys(patch).length)changes.push({kind:r.kind,id:r.id,version:r.version,patch});
  }if(!changes.length)throw Error('Belum ada perubahan.');await api('/api/bulk-edit',{method:'PUT',body:{rows:changes}});
 },{wide:true,save:'Simpan Semua'});
 const nodes=$$('[data-bulk-row]');
 const drawRecipe=n=>{const target=nodes[n].querySelector('.bulk-nested');target.innerHTML=recipes[n].map((r,j)=>'<div class="form-grid" data-recipe-line="'+j+'">'+input(['stockId','Barang Stok Teko',stocks.map(s=>({id:s.id,name:s.name+' ('+s.unit+')'}))],r.stockId,'sr'+n+'_'+j+'_')+input(['quantity','Pemakaian per produk','number'],r.quantity,'sr'+n+'_'+j+'_')+'<button type="button" class="secondary" data-remove="'+j+'">Hapus barang</button></div>').join('')+'<button type="button" class="secondary" data-add>Tambah barang stok</button>';target.querySelectorAll('[data-recipe-line]').forEach(row=>{const j=Number(row.dataset.recipeLine);row.querySelector('select').onchange=e=>recipes[n][j].stockId=e.target.value;const number=row.querySelector('input');number.step='0.001';number.min='0.001';number.oninput=e=>recipes[n][j].quantity=Number(e.target.value);});target.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{recipes[n].splice(Number(b.dataset.remove),1);drawRecipe(n);});target.querySelector('[data-add]').onclick=()=>{if(recipes[n].length>=50)return;recipes[n].push({stockId:'',quantity:1});drawRecipe(n);};};
 const drawItems=n=>{const r=entries[n],invoice=r.kind==='invoices',target=nodes[n].querySelector('.bulk-nested'),products=invoice?(lookups.products||[]):queueProducts;
  target.innerHTML='<h3>Rincian produk</h3>'+itemRows[n].map((i,j)=>'<div class="form-grid" data-item-line="'+j+'">'+input(['productId','Produk',products.map(p=>({id:p.id,name:p.name}))],i.productId,'it'+n+'_'+j+'_')+(invoice?['name','unit','price','discount','notes'].map(k=>input([k,({name:'Nama pada invoice',unit:'Satuan',price:'Harga',discount:'Diskon item',notes:'Catatan'})[k],['price','discount'].includes(k)?'number':'text',k!=='notes'],i[k]??(['price','discount'].includes(k)?0:''),'it'+n+'_'+j+'_')).join(''):'')+input(['qty','Jumlah','number'],i.qty,'it'+n+'_'+j+'_')+'<button type="button" class="secondary" data-remove="'+j+'">Hapus item</button></div>').join('')+'<button type="button" class="secondary" data-add>Tambah produk</button>';
  target.querySelectorAll('[data-item-line]').forEach(row=>{const j=Number(row.dataset.itemLine);row.querySelectorAll('[data-bulk-field]').forEach(c=>{if(c.type==='number'){c.step=c.dataset.bulkField==='qty'&&invoice?'0.001':'1';}c.onchange=()=>{const k=c.dataset.bulkField;itemRows[n][j][k]=c.type==='number'?Number(c.value):c.value;if(k==='productId'){const p=products.find(p=>p.id===c.value);if(p){itemRows[n][j]={productId:p.id,name:p.name,unit:p.unit,price:p.price,discount:0,notes:'',qty:itemRows[n][j].qty||1};drawItems(n);}}};});});target.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{itemRows[n].splice(Number(b.dataset.remove),1);drawItems(n);});target.querySelector('[data-add]').onclick=()=>{itemRows[n].push({productId:'',qty:1,name:'',unit:'',price:0,discount:0});drawItems(n);};
 };
 nodes.forEach((el,n)=>{const r=entries[n],get=k=>el.querySelector(':scope > .form-grid [data-bulk-field="'+k+'"]');if(mode==='stock'){drawRecipe(n);return;}if(['sales','expenses'].includes(r.kind))bindFinanceFields(r.kind,get);if(r.kind==='procurements')bindProcurementFields(get);for(const k of ['quantity','minTeko','maxTeko','minWarehouse','maxWarehouse'])if(get(k))get(k).step='0.001';if(['invoices','posorders'].includes(r.kind))drawItems(n);
  if(r.kind==='users'){const target=el.querySelector('.bulk-nested'),draw=p=>{target.innerHTML='<details><summary>Izin akses</summary>'+session.modules.map(m=>'<fieldset><legend>'+esc(m)+'</legend>'+session.actions.map(a=>'<label><input type="checkbox" data-permission="'+esc(m)+'" value="'+esc(a)+'" '+((p[m]||[]).includes(a)?'checked':'')+'>'+esc(a)+'</label>').join('')+'</fieldset>').join('')+'</details>';};draw(r.data.permissions||{});get('role').onchange=()=>draw(session.roles[get('role').value]);}
 });
 if(mode==='stock')$('#copyRecipe').onclick=()=>{if(!confirm('Ganti susunan stok semua produk pilihan dengan susunan produk pertama?'))return;for(let n=1;n<recipes.length;n++){recipes[n]=structuredClone(recipes[0]);drawRecipe(n);}};
}
