const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {createPlatform}=require('../server.cjs');
const {chromium}=require('C:/Users/LENOVO.MGA23/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{
 const app=createPlatform({dataDir:fs.mkdtempSync(path.join(require('node:os').tmpdir(),'marala-browser-'))});
 await new Promise(r=>app.server.listen(0,'127.0.0.1',r));
 const base='http://127.0.0.1:'+app.server.address().port,browser=await chromium.launch({headless:true,channel:'msedge'}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 const out=path.join(__dirname,'artifacts');fs.mkdirSync(out,{recursive:true});
 try{
 await page.goto(base);await page.locator('.choice').first().waitFor();
 assert.equal(await page.locator('.marala-wa').count(),2);assert.ok(await page.evaluate(()=>document.querySelector('#marala-preview').getBoundingClientRect().width===innerWidth));assert.equal(await page.locator('.marala-wa-float').evaluate(el=>getComputedStyle(el).position),'fixed');assert.ok((await page.locator('.marala-wa-top').getAttribute('href')).startsWith('https://wa.me/6282317393231?text='));
 assert.equal(await page.locator('.brand-text strong').innerText(),'MaralaKu');assert.equal(await page.locator('.mode-switch a[href="/"]').innerText(),'Kenali MaralaKu');assert.ok(decodeURIComponent(await page.locator('.marala-wa-top').getAttribute('href')).includes('bertanya tentang Kasir Marala'));
 assert.equal(await page.locator('#paket-usaha').count(),0);await page.locator('.mode-switch a[href="/paket-usaha"]').click();await page.waitForURL('**/paket-usaha');await page.locator('#package-order').waitFor();await page.locator('[data-plan="yearly"]').click();assert.equal(await page.locator('#package-order [name="plan"]').inputValue(),'yearly');for(const [key,value]of Object.entries({owner:'Dewo',business:'Toko & Usaha Dewo',phone:'ngasal',notes:'Butuh kasir dan stok'}))await page.locator(`#package-order [name="${key}"]`).fill(value);await page.locator('#package-order [name="type"]').selectOption('toko');await page.locator('#package-order [name="consent"]').check();await page.locator('.package-send').click();assert.equal(await page.locator('#package-order [name="phone"]').getAttribute('aria-invalid'),'true');await page.locator('#package-order [name="phone"]').fill('081234567890');await page.locator('#package-order [name="assistance"]').check();let orderMessage='';await page.context().route('https://wa.me/**',route=>{orderMessage=new URL(route.request().url()).searchParams.get('text');return route.fulfill({status:200,contentType:'text/html',body:'Test: WhatsApp handoff intercepted.'});});const popupPromise=page.waitForEvent('popup');await page.locator('.package-send').click();const popup=await popupPromise;await popup.waitForLoadState();assert.ok(orderMessage.includes('Rp490.000'));assert.ok(orderMessage.includes('WhatsApp: +6281234567890'));assert.ok(orderMessage.includes('Toko & Usaha Dewo'));assert.ok(orderMessage.includes('mulai Rp150.000'));await popup.close();await page.screenshot({path:path.join(out,'package-order.png')});await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(out,'package-mobile.png'),fullPage:true});await page.setViewportSize({width:1440,height:1000});await page.goto(base);
 await page.screenshot({path:path.join(out,'home.png'),fullPage:true});
 await page.goto(base+'/register?type=toko');
 assert.equal(await page.locator('#register [name="email"]').count(),0);
 for(const [name,value] of Object.entries({business:'Toko Pengujian',owner:'Dewo',username:'dewo',phone:'081234567890',password:'Marala-test-2026'}))await page.locator(`[name="${name}"]`).fill(value);
 await page.locator('input[type=checkbox][required]').check();await page.locator('[name="phone"]').fill('ngasal');await page.locator('#register button').click();await page.locator('#register-phone-error').waitFor();assert.equal(await page.locator('[name="phone"]').getAttribute('aria-invalid'),'true');assert.equal(await page.locator('#message').innerText(),'');assert.ok(await page.locator('#register-phone-error').evaluate(el=>el.parentElement.querySelector('input')?.name==='phone'));await page.screenshot({path:path.join(out,'phone-validation.png'),fullPage:true});await page.locator('[name="phone"]').fill('081234567890');
 await page.locator('input[type=checkbox][required]').check();await page.locator('#register button').click();
 await page.waitForURL('**/workspace');await page.locator('#guide-close').click({timeout:15000});
 await page.locator('#marala-trial-bar').waitFor();await page.screenshot({path:path.join(out,'workspace.png'),fullPage:true});
 await page.locator('.topbar .marala-wa-top').waitFor();assert.equal(await page.locator('.marala-wa').count(),2);
 assert.equal(await page.locator('.nav > a,.nav > details').count(),8);
 assert.equal(await page.locator('#marala-menu-mode').count(),0);
 const reportMenu=page.locator('.nav-section').filter({has:page.locator('[data-nav="profit"]')});await reportMenu.locator('summary').click();assert.equal(await reportMenu.locator('.nav-group-title').evaluate(el=>getComputedStyle(el).transform),'none');assert.equal(await reportMenu.locator('.nav-group-title').innerText(),'Laporan');await page.locator('#themeButton').click();await page.screenshot({path:path.join(out,'simple-menu-dark.png')});await page.locator('#themeButton').click();
 await page.locator('[data-nav="poscashier"]').click();await page.waitForTimeout(800);await page.screenshot({path:path.join(out,'cashier.png'),fullPage:true});
 assert.ok((await page.locator('body').innerText()).includes('Beras'));
 await page.setViewportSize({width:390,height:844});await page.waitForTimeout(350);await page.screenshot({path:path.join(out,'cashier-mobile.png'),fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.setViewportSize({width:1440,height:1000});await page.waitForTimeout(350);
 await page.locator('[data-pos-check]').first().check();await page.locator('#posPay [name="cash"]').fill('100000');await page.locator('#posPay button[type="submit"],#posPay button.primary').first().click();await page.waitForTimeout(500);assert.equal(await page.evaluate(async()=>{const r=await fetch('/api/pos/tickets');return (await r.json()).length;}),1);
 await page.goto(base+'/admin');
 for(const [name,value] of Object.entries({name:'Admin BUMM',email:'admin@example.test',password:'Marala-test-2026'}))await page.locator(`[name="${name}"]`).fill(value);
 await page.locator('#login button').click();await page.waitForTimeout(800);
 assert.ok((await page.locator('body').innerText()).includes('Toko Pengujian'));
 assert.ok((await page.locator('body').innerText()).includes('+6281234567890'));await page.locator('[data-id]').first().click();assert.ok((await page.locator('a[href^="https://wa.me/"]').getAttribute('href')).startsWith('https://wa.me/6281234567890?text='));
 await page.screenshot({path:path.join(out,'admin.png'),fullPage:true});
 assert.equal(await page.locator('.mode-switch a[href="/login"]').count(),0);
 for(const type of ['kafe','jasa']){
 const context=await browser.newContext({viewport:{width:1440,height:1000}}),p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/register?type='+type);
 for(const [name,value] of Object.entries({business:type==='jasa'?'Studio Dewo':'Kafe Dewo',owner:'Dewo',username:'dewo',phone:type==='jasa'?'081234567892':'081234567891',password:'Marala-test-2026'}))await p.locator(`[name="${name}"]`).fill(value);
 await p.locator('input[type=checkbox][required]').check();await p.locator('#register button').click();await p.waitForURL('**/workspace');await p.locator('#guide-close').click();await p.locator('#marala-trial-bar').waitFor();assert.equal(await p.locator('.nav > a,.nav > details').count(),8);assert.equal(await p.locator('[data-nav="attendance"]').count(),0);assert.equal(await p.locator('[data-nav="poscashier"]').count(),type==='jasa'?0:1);
 await p.screenshot({path:path.join(out,type+'-workspace.png'),fullPage:true});await p.locator(`[data-nav="${type==='jasa'?'invoices':'posqueue'}"]`).click();await p.waitForTimeout(300);await p.screenshot({path:path.join(out,type+'-main.png'),fullPage:true});await context.close();
 }
 await page.setViewportSize({width:390,height:844});await page.goto(base);await page.waitForTimeout(300);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(out,'mobile.png'),fullPage:true});
 assert.equal(await page.locator('a[href="/admin"]').count(),0);await page.goto(base+'/login');assert.equal(await page.locator('#login [name="email"]').count(),0);await page.locator('[name="phone"]').fill('+62 812-3456-7890');await page.locator('[name="password"]').fill('Marala-test-2026');await page.locator('#login button').click();await page.waitForURL('**/workspace');await page.locator('#marala-trial-bar').waitFor();assert.deepEqual(errors,[]);console.log('Browser passed: WA signup/login, admin follow-up link, three business menus, cashier, invoice and mobile layout.');
 }catch(e){console.log('ERRORS',errors);console.log((await page.locator('body').innerText()).slice(0,3000));await page.screenshot({path:path.join(out,'error.png'),fullPage:true});throw e;}finally{await browser.close();await new Promise(r=>app.server.close(r));app.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
