const {createPlatform}=require('../server.cjs'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require('C:/Users/LENOVO.MGA23/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const app=createPlatform({dataDir:fs.mkdtempSync(path.join(os.tmpdir(),'marala-money-'))});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+app.server.address().port,browser=await chromium.launch({headless:true,channel:'msedge'});try{
 const page=await browser.newPage({viewport:{width:390,height:844}});
 const register=await page.request.post(base+'/platform/register',{data:{business:'Usaha Nominal Besar',owner:'Dewo',username:'dewo',phone:'081234567887',password:'Password12345',type:'toko',samples:true}});assert.equal(register.status(),201);
 const product=await page.request.post(base+'/api/pos/products',{data:{name:'Produk nominal besar',category:'Tes',price:1000000000000,cost:0,active:true}});assert.equal(product.status(),201);const id=(await product.json()).id;
 await page.goto(base+'/workspace');await page.locator('#guide-close').click();await page.locator('.metric strong').first().waitFor();
 async function check(selector){const results=await page.locator(selector).evaluateAll(nodes=>nodes.map(el=>{const r=document.createRange();r.selectNodeContents(el);const rects=[...r.getClientRects()];const b=el.getBoundingClientRect();return {text:el.textContent,lines:new Set(rects.map(x=>Math.round(x.top))).size,within:rects.every(x=>x.right<=b.right+1&&x.left>=b.left-1)};}));assert.ok(results.length);for(const r of results){assert.equal(r.lines,1,JSON.stringify(r));assert.ok(r.within,JSON.stringify(r));}assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
 for(const width of [320,360,390,430]){await page.setViewportSize({width,height:844});await page.locator('.metric strong').evaluateAll(nodes=>nodes.forEach((n,i)=>n.textContent=(i===3?'-Rp ':'Rp ')+(i===0?'100.000':'1.000.000.000.000')));await check('.metric strong');}
 await page.setViewportSize({width:390,height:844});const out=path.join(__dirname,'artifacts');fs.mkdirSync(out,{recursive:true});await page.screenshot({path:path.join(out,'money-dashboard-mobile.png'),fullPage:true});
 await page.setViewportSize({width:1440,height:1000});await page.locator('[data-nav="poscashier"]').click();await page.locator('#posSearch').fill('Produk nominal besar');await page.locator('[data-pos-check="'+id+'"]').check();
 for(const width of [320,360,390,430]){await page.setViewportSize({width,height:844});await check('#posMobileTotal');await check('#posTotals h2 .marala-money');await check('.pos-product:visible .marala-money');}
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(out,'money-cashier-mobile.png'),fullPage:true});console.log('Mobile money passed: 320, 360, 390, 430px; Rp100.000 and +/-Rp1.000.000.000.000 remain complete without wrapping or clipping.');
 }finally{await browser.close();await new Promise(r=>app.server.close(r));app.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
