const crypto=require('node:crypto');
const {GROUP,MODULES,ACTIONS,rolePermissions,passwordOK,today,fail}=require('./domain.cjs');
const {xlsx,readXlsx,readCsv,csv}=require('./workbook.cjs');
const {migrate}=require('./migrate.cjs');
const IMPORT_FIELDS=['number','date','category','description','unit','amount','method','source','status','notes'];
function createHandler({store,secureCookies=false,setupTokenRequired=false,authorizeSetup,legacySeed,attempts=new Map()}){
 const gate=(u,m,a)=>{if(!store.can(u,m,a))fail('Anda tidak memiliki izin untuk tindakan ini.',403);};
 const userFor=req=>{const token=(req.headers.cookie||'').match(/(?:^|;\s*)marala_session=([a-f0-9]+)/)?.[1];if(!token)return null;const row=store.db.prepare('SELECT user_id FROM sessions WHERE token=? AND expires>?').get(crypto.createHash('sha256').update(token).digest('hex'),Date.now());return row?store.user(row.user_id):null;};
 const json=(res,data,status=200)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data));};
 const body=async req=>{let b=Buffer.alloc(0);for await(const part of req){b=Buffer.concat([b,part]);if(b.length>8e6)fail('Data terlalu besar (maksimal 8 MB).',413);}try{return JSON.parse(b.toString()||'{}');}catch{fail('Format JSON tidak valid.');}};
 function archiveExport(res,saved,f){const kind=f.kind||'profit';if(!['profit','revenue','opnamereport'].includes(kind))fail('Jenis laporan tidak dikenal.');const rows=kind==='profit'?saved.sheets[0].rows.map(row=>row.map(v=>v&&typeof v==='object'?v.value:v)):kind==='revenue'?saved.revenueRows:saved.opnameRows;const format=f.format==='csv'?'csv':'xlsx';res.writeHead(200,{'Content-Type':format==='csv'?'text/csv; charset=utf-8':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','Content-Disposition':'attachment; filename="DISETUJUI_'+kind+'_'+saved.from+'_'+saved.to+'.'+format+'"','Cache-Control':'no-store'});return res.end(format==='csv'?csv(rows):kind==='profit'?require('./finance-export.cjs').workbook(saved.sheets):xlsx(rows));}
 function getRows(kind,f){let rows=store.list(kind,kind==='stocks'?{unitId:f.unitId,location:f.location,q:f.q}:kind==='transfers'?{...f,location:undefined}:f);if(['stockitems','stocks','movements','opnames','transfers'].includes(kind))rows=require('./inventory.cjs').categorize(store,kind,rows,f);if(kind==='opnames')rows=require('./opname-usage.cjs').enrich(store,rows);if(kind==='sales')rows=rows.map(require('./live-cost.cjs').calculator(store).sale);if(kind==='invoices')rows=rows.map(i=>store.invoiceView(i));if(kind==='stocks')rows=rows.map(s=>store.stockView(s,f.to));return rows.map(r=>store.provenance({...r,kind}));}
 function exportRows(kind,f){const label={salesUsed:'Terpakai dari Penjualan',code:'Kode',minTeko:'Minimum Teko',maxTeko:'Maksimum Teko',minWarehouse:'Minimum Gudang',maxWarehouse:'Maksimum Gudang',costClass:'Kelompok Biaya',unitPrice:'Harga Satuan',recipient:'Penerima',payPeriod:'Periode Gaji',invoiceId:'Invoice Terkait',salePrice:'Harga Jual Satuan',unitCost:'HPP Satuan',marketing:'Marketing',customerName:'Customer',type:'Jenis Pengadaan',bankId:'Rekening',assetCategory:'Kategori Aset',assetLocation:'Lokasi Aset',cost:'HPP',grossProfit:'Profit Kotor',number:'Nomor',date:'Tanggal',name:'Nama',unitId:'Unit Bisnis',productId:'Produk',customerId:'Customer',total:'Total Tagihan',paid:'Sudah Dibayarkan',balance:'Sisa Pembayaran',status:'Status',amount:'Nominal',location:'Lokasi',quantity:'Jumlah',unit:'Satuan',price:'Harga Satuan',value:'Nilai Stok',description:'Deskripsi',category:'Kategori',source:'Sumber Dana',method:'Metode',letterNumber:'Nomor Surat',applicant:'Pengaju',system:'Stok Sistem',actual:'Stok Aktual',difference:'Selisih',differenceValue:'Nilai Selisih',notes:'Catatan',direction:'Jenis Mutasi'};
 if(kind==='profit'||kind==='revenue'){const r=store.report(f);return kind==='profit'?[...require('./finance-export.cjs').sheets(store,r,{name:'Ekspor aplikasi'})[0].rows.map(row=>row.map(v=>v&&typeof v==='object'?v.value:v)),[],['Catatan'],...r.warnings.map(w=>[w.number,w.date,w.message])]:[['Laporan Omzet Berdasarkan Uang Masuk',f.from||'Semua',f.to||'Semua'],['Unit Bisnis','Omzet'],...r.units.filter(u=>!f.unitId||u.id===f.unitId).map(u=>[u.name,u.revenue]),['Total Omzet',r.revenue],['Jumlah Pembayaran / Penjualan',r.count],[],['Tanggal Masuk','Nomor','Unit Bisnis','Keterangan','Omzet','HPP'],...r.entries.map(e=>[e.date,e.number,e.unitName,e.description,e.amount,e.cost])];}

 const rows=getRows(kind,f),keys=({products:['code','name','unitId','type','unit','cost','price'],procurements:['number','date','type','unitId','name','description','quantity','unit','price','amount','source','bankId','method','status','assetCategory','assetLocation','notes'],referrals:['customerName','marketing','amount','date','notes'],invoices:['number','date','customerId','unitId','total','paid','balance','status'],payments:['date','invoiceId','customerName','method','amount'],stockitems:['name','unit','minTeko','minWarehouse','maxTeko','maxWarehouse','price','category'],transfers:['number','date','name','from','to','quantity','unit','value','notes','category'],stocks:['name','location','unit','quantity','price','value','status','category'],movements:['date','name','location','direction','quantity','price','notes','category'],opnames:['date','name','location','unit','salesUsed','system','actual','difference','price','differenceValue','notes','category'],expenses:['number','date','category','costClass','description','unitId','quantity','unit','unitPrice','amount','recipient','payPeriod','invoiceId','method','source','status','notes'],requests:['number','letterNumber','date','applicant','unitId','description','amount','status','notes'],sales:['number','date','unitId','productName','description','quantity','unit','salePrice','unitCost','amount','cost','grossProfit','method']})[kind]||['name'];
 return [keys.map(k=>label[k]||k),...rows.map(r=>keys.map(k=>{if(kind==='sales'&&k==='grossProfit')return Number(r.amount||0)-Number(r.cost||0);if(kind==='sales'&&k==='cost')return Number(r.cost||0);if(['unitId','productId','customerId','invoiceId','bankId'].includes(k)&&r[k]){const x=store.get(r[k],null,true);return x.name||x.number;}return r[k]??(k==='salesUsed'?'—':'');}))];}
 function preview(data){const rows=data.format==='xlsx'?readXlsx(Buffer.from(data.content,'base64')):readCsv(data.content);if(rows.length>2001)fail('Maksimal 2.000 baris per impor.');if(!rows.length||IMPORT_FIELDS.some((k,i)=>rows[0][i]!==k))fail('Kolom tidak sesuai template. Unduh template terlebih dahulu.');const seen=new Set();return store.preview(()=> rows.slice(1).map((r,index)=>{const d=Object.fromEntries(IMPORT_FIELDS.map((k,i)=>[k,r[i]??'']));const unit=store.list('units').find(u=>u.name.toLowerCase()===String(d.unit).toLowerCase());d.unitId=unit?.id;if(data.format==='xlsx'&&/^\d{4,6}$/.test(String(d.date))){d.date=new Date(Date.UTC(1899,11,30)+Number(d.date)*86400000).toISOString().slice(0,10);}d.amount=Number(d.amount);d.proof='';let error='';if(d.number&&seen.has(d.number))error='Nomor transaksi duplikat dalam file.';if(d.number)seen.add(d.number);if(!error){try{store.tx(()=>store.save('expenses',d,undefined,'preview'));}catch(e){error=e.message.includes('UNIQUE')?'Nomor transaksi sudah terdaftar.':e.message;}}return {row:index+2,data:d,error};}));}
 return async(req,res)=>{try{
  res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','DENY');res.setHeader('Referrer-Policy','same-origin');
  const url=new URL(req.url,'http://localhost'),p=url.pathname,f=Object.fromEntries(url.searchParams),method=req.method;
  if(!['GET','HEAD'].includes(method)){const origin=req.headers.origin;if(origin&&new URL(origin).host!==req.headers.host)fail('Origin permintaan tidak diizinkan.',403);if(req.headers['sec-fetch-site']==='cross-site')fail('Permintaan lintas situs ditolak.',403);if(!String(req.headers['content-type']).startsWith('application/json'))fail('Gunakan JSON.',415);}
  if((p==='/manifest.webmanifest'||p==='/api/application-brand'||p==='/api/application-icon')&&['GET','HEAD'].includes(method)){
   const app=store.setting('application')||{name:'BUMM Marala Management System',shortName:'BUMM Marala'},version=app.version||'default';
   if(p==='/api/application-brand')return json(res,{name:app.name,icon:app.icon512?'/api/application-icon?size=512&v='+version:'/icon.svg'});
   if(p==='/api/application-icon'){const icon=f.size==='192'?app.icon192:app.icon512;if(!icon)fail('Ikon belum diatur.',404);res.writeHead(200,{'Content-Type':'image/png','Cache-Control':'no-cache'});return res.end(method==='HEAD'?undefined:Buffer.from(icon.split(',')[1],'base64'));}
   res.writeHead(200,{'Content-Type':'application/manifest+json','Cache-Control':'no-cache'});return res.end(method==='HEAD'?undefined:JSON.stringify({id:'/index.html',name:app.name,short_name:app.shortName,start_url:'/index.html',scope:'/',display:'standalone',background_color:'#f5f8fc',theme_color:'#0b4ea2',icons:app.icon512?[192,512].map(size=>({src:'/api/application-icon?size='+size+'&v='+version,sizes:size+'x'+size,type:'image/png',purpose:'any'})):[{src:'/icon.svg',sizes:'any',type:'image/svg+xml',purpose:'any maskable'}]}));
  }
  const user=userFor(req),setup=store.db.prepare('SELECT count(*) n FROM users').get().n===0;
  if(p==='/api/session'&&method==='GET')return json(res,{setup,setupTokenRequired,user,modules:MODULES,actions:ACTIONS,roles:Object.fromEntries(['SUPER ADMIN','ADMIN','STAFF','VIEWER'].map(r=>[r,rolePermissions(r)]))});
  if(p==='/api/setup'&&method==='POST'){if(!setup)fail('Admin utama sudah dibuat.',409);const d=await body(req);authorizeSetup(req,d);const u=store.tx(()=>{if(store.db.prepare('SELECT count(*) n FROM users').get().n)fail('Admin utama sudah dibuat.',409);return store.saveUser({...d,role:'SUPER ADMIN',active:true},null,'setup');});return json(res,u,201);}
  if(p==='/api/login'&&method==='POST'){const ip=req.socket.remoteAddress,entry=attempts.get(ip)||{count:0,until:0};if(entry.until>Date.now())fail('Terlalu banyak percobaan. Coba lagi dalam 15 menit.',429);const d=await body(req),u=store.db.prepare('SELECT * FROM users WHERE username=? AND active=1 AND deleted=0').get(String(d.username||'').toLowerCase());if(!u||!passwordOK(d.password,u.password)){entry.count++;if(entry.count>=8)entry.until=Date.now()+900000;attempts.set(ip,entry);fail('Username atau password salah.',401);}attempts.delete(ip);const token=crypto.randomBytes(32).toString('hex');store.db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(crypto.createHash('sha256').update(token).digest('hex'),u.id,Date.now()+12*3600000);res.setHeader('Set-Cookie',`marala_session=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=43200${secureCookies?'; Secure':''}`);return json(res,{user:store.user(u.id)});}
  if(p.startsWith('/api/')){
   if(!user?.active)fail('Silakan masuk terlebih dahulu.',401);
   if(p.startsWith('/api/attendance')){const a=require('./attendance.cjs');
    if(p==='/api/attendance'&&method==='GET')return json(res,a.view(store,user,f));
    if(p==='/api/attendance/punch'&&method==='POST')return json(res,a.punch(store,user,(await body(req)).action));
    if(p==='/api/attendance/settings'&&method==='GET')return json(res,a.settings(store,user));
    if(p==='/api/attendance/settings'&&method==='POST')return json(res,a.saveSchedule(store,user,await body(req)));
    if(p==='/api/attendance/export'&&method==='GET'){const sheets=require('./attendance-export.cjs').sheets(store,user,f);res.writeHead(200,{'Content-Type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','Content-Disposition':'attachment; filename="Rekap_Absensi_'+(f.from||'awal')+'_'+(f.to||'semua')+'.xlsx"','Cache-Control':'no-store'});return res.end(require('./finance-export.cjs').workbook(sheets));}
    if(p==='/api/attendance/recap'&&method==='GET')return json(res,a.recap(store,user,f));
    if(p==='/api/attendance/overtime'&&method==='POST')return json(res,a.overtime(store,user,await body(req)));
    fail('Menu absensi tidak ditemukan.',404);
   }
   if(p==='/api/contacts'||p.startsWith('/api/contacts/')){
    const contacts=require('./contacts.cjs');gate(user,'customers','view');
    if(p==='/api/contacts'&&method==='GET')return json(res,contacts.list(store,f));
    if(p==='/api/contacts'&&method==='POST'){gate(user,'customers','create');return json(res,contacts.save(store,await body(req),undefined,user.id),201);}
    if(p==='/api/contacts/preview'&&method==='POST'){gate(user,'customers','create');return json(res,contacts.preview(store,await body(req)));}
    if(p==='/api/contacts/import'&&method==='POST'){gate(user,'customers','create');return json(res,contacts.commit(store,await body(req),user.id));}
    if(p==='/api/contacts/template'&&method==='GET'){gate(user,'customers','create');res.writeHead(200,{'Content-Type':'text/csv; charset=utf-8','Content-Disposition':'attachment; filename="Template_Kontak.csv"'});return res.end('\uFEFF'+csv([['Nama','WhatsApp','Kategori','Keterangan']]));}
    if(p==='/api/contacts/export'&&method==='GET'){gate(user,'customers','export');res.writeHead(200,{'Content-Type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','Content-Disposition':'attachment; filename="Database_Kontak.xlsx"'});return res.end(xlsx([['Nama','WhatsApp','Kategori','Keterangan','Sumber','Diinput oleh'],...contacts.list(store,f).map(r=>[r.name,r.phone,r.category||'',r.notes||'',r.source,r._trace?.createdBy?.name||''])]));}
    const match=p.match(/^\/api\/contacts\/([^/]+)$/);
    if(match&&method==='PUT'){gate(user,'customers','edit');return json(res,contacts.save(store,await body(req),match[1],user.id));}
    if(match&&method==='DELETE'){gate(user,'customers','delete');return json(res,store.tx(()=>{store.get(match[1],'contacts');store.remove('contacts',match[1],user.id);return {ok:true};}));}
    fail('Menu kontak tidak ditemukan.',404);
   }
   if(p==='/api/bulk-edit/read'&&method==='POST')return json(res,require('./bulk-edit.cjs').read(store,user,(await body(req)).rows));
   if(p==='/api/bulk-edit'&&method==='PUT'){const result=require('./bulk-edit.cjs').save(store,user,(await body(req)).rows);return json(res,{count:result.length});}
   const approvals=require('./report-approvals.cjs');
   if(p==='/api/report-approvals'&&method==='GET'){gate(user,'reports','view');return json(res,approvals.list(store));}
   if(p==='/api/report-approvals/preview'&&method==='GET'){gate(user,'reports','view');const scope=approvals.period(f),existing=approvals.exact(store,scope);return json(res,existing?{...approvals.get(store,existing.id),approved:true}:approvals.prepare(store,scope));}
   if(p==='/api/report-approvals'&&method==='POST'){
    if(user.role!=='SUPER ADMIN')fail('Hanya Super Admin dapat menyetujui laporan.',403);
    const key='approval:'+user.id,entry=attempts.get(key)||{count:0,until:0};if(entry.until>Date.now())fail('Terlalu banyak password salah. Coba lagi dalam 15 menit.',429);
    try{const result=approvals.approve(store,await body(req),user);attempts.delete(key);return json(res,result,201);}catch(e){if(e.status===403){entry.count++;if(entry.count>=5)entry.until=Date.now()+900000;attempts.set(key,entry);}throw e;}
   }
   const archive=p.match(/^\/api\/report-approvals\/([^/]+)(?:\/(export))?$/);
   if(archive&&method==='GET'){gate(user,'reports','view');const saved=approvals.get(store,archive[1]);if(archive[2]){gate(user,'reports','export');return archiveExport(res,saved,f);}return json(res,{...saved,approved:true});}
   if(p==='/api/activity'&&method==='GET'){
    let data;
    if(f.recordId){const record={...store.get(f.recordId,null,true),kind:store.db.prepare('SELECT kind FROM records WHERE id=?').get(f.recordId).kind},module=GROUP[record.kind]||({posproducts:'posmaster',postickets:'pos',posdays:'posapproval',poshistory:'posapproval'})[record.kind];if(!module)fail('Riwayat tidak tersedia.',404);gate(user,module,'view');data=store.activityEvents().filter(e=>e.recordId===f.recordId||e.entity===f.recordId||e.entity===record.kind+':'+f.recordId);return json(res,{record:store.provenance({...record,kind:record.kind}),events:data});}
    if(user.role!=='SUPER ADMIN')fail('Riwayat seluruh sistem hanya untuk Super Admin.',403);
    const limit=100,offset=Math.max(0,Number(f.offset)||0);if(f.from)require('./domain.cjs').date(f.from);if(f.to)require('./domain.cjs').date(f.to);if(f.from&&f.to&&f.from>f.to)fail('Rentang tanggal tidak valid.');data=store.activityEvents().filter(e=>(!f.from||e.date>=f.from)&&(!f.to||e.date<=f.to)&&(!f.q||JSON.stringify(e).toLowerCase().includes(f.q.toLowerCase())));return json(res,{total:data.length,events:data.slice(offset,offset+limit),offset,limit});
   }
   if(p.startsWith('/api/pos/')){
    const pos=require('./pos.cjs');
    if(p==='/api/pos/history'&&method==='GET'){gate(user,'pos','view');return json(res,require('./pos-history.cjs').history(store,f));}
    if(p==='/api/pos/orders'&&method==='GET'){gate(user,'pos','view');let rows=store.list('posorders',f);if(f.type)rows=rows.filter(r=>r.orderType===f.type);if(f.status)rows=rows.filter(r=>r.status===f.status);return json(res,rows);}
    const order=p.match(/^\/api\/pos\/orders\/([^/]+)\/(pay|status|debt|cancel|edit)$/);if(order&&method==='POST'){gate(user,'pos',order[2]==='pay'?'create':'edit');return json(res,pos.changeOrder(store,order[1],await body(req),order[2],user.id));}
    if(p==='/api/pos/day/delete'&&method==='POST'){gate(user,'posapproval','delete');return json(res,pos.deleteDay(store,await body(req),user));}
    if(p==='/api/pos/stock-options'&&method==='GET'){gate(user,'posmaster','view');return json(res,store.list('stocks',{location:'Teko Marala'}).map(({id,name,unit})=>({id,name,unit})));}
    if(p==='/api/pos/products'){
     if(method==='GET'){if(!store.can(user,'pos','view')&&!store.can(user,'posmaster','view'))fail('Akses ditolak.',403);return json(res,store.list('posproducts'));}
     if(method==='POST'){gate(user,'posmaster','create');const d=await body(req);return json(res,pos.saveProduct(store,d,undefined,user.id),201);}
    }
    if(p==='/api/pos/products/export'&&method==='GET'){gate(user,'posmaster','view');gate(user,'posmaster','export');const rows=[['Produk','Kategori','Harga Jual','HPP Standar','Status','Pemakaian Stok Teko per Produk'],...store.list('posproducts').map(p=>[p.name,p.category,p.price,p.cost,p.active?'Aktif':'Nonaktif',(p.stockRecipe||[]).map(r=>r.name+': '+r.quantity+' '+r.unit).join('; ')])],isCsv=f.format==='csv';res.writeHead(200,{'Content-Type':isCsv?'text/csv; charset=utf-8':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','Content-Disposition':'attachment; filename="Master_Produk_Teko.'+(isCsv?'csv':'xlsx')+'"','Cache-Control':'no-store'});return res.end(isCsv?csv(rows):xlsx(rows));}
    const prod=p.match(/^\/api\/pos\/products\/([^/]+)$/);if(prod&&method==='DELETE'){gate(user,'posmaster','delete');return json(res,store.tx(()=>{store.get(prod[1],'posproducts');store.remove('posproducts',prod[1],user.id);return {ok:true};}));}if(prod&&method==='PUT'){gate(user,'posmaster','edit');return json(res,pos.saveProduct(store,await body(req),prod[1],user.id));}
    if(p==='/api/pos/products-batch'&&method==='POST'){gate(user,'posmaster','create');const d=await body(req);if(!Array.isArray(d.rows)||!d.rows.length||d.rows.length>100)fail('Isi 1–100 produk.');return json(res,store.tx(()=>d.rows.map(r=>pos.saveProduct(store,r,undefined,user.id))),201);}
    if(p==='/api/pos/tickets'){
     gate(user,'pos',method==='POST'?'create':'view');if(method==='GET')return json(res,store.list('postickets',f));if(method==='POST')return json(res,pos.createSale(store,await body(req),user.id),201);
    }
    const ticket=p.match(/^\/api\/pos\/tickets\/([^/]+)\/void$/);if(ticket&&method==='POST'){gate(user,'pos','edit');return json(res,pos.voidSale(store,ticket[1],(await body(req)).reason,user.id));}
    const action=p.match(/^\/api\/pos\/day\/(submit|approve|reopen)$/);if(action&&method==='POST'){gate(user,'posapproval',action[1]==='submit'?'create':'approve');return json(res,pos.changeDay(store,await body(req),action[1],user));}
    if(p==='/api/pos/report'&&method==='GET'){if(!store.can(user,'posreports','view')&&!store.can(user,'posapproval','view'))fail('Akses ditolak.',403);return json(res,pos.report(store,f.month||today().slice(0,7),f));}
    if(p==='/api/pos/export'&&method==='GET'){gate(user,'posreports','view');gate(user,'posreports','export');const report=pos.report(store,f.month||today().slice(0,7),f);res.writeHead(200,{'Content-Type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','Content-Disposition':'attachment; filename="Teko_Marala_'+report.month+'.xlsx"'});return res.end(require('./workbook.cjs').xlsxSheets(pos.sheets(report)));}
    fail('API kasir tidak ditemukan.',404);
   }
   if(p==='/api/logout'&&method==='POST'){const token=(req.headers.cookie||'').match(/marala_session=([a-f0-9]+)/)?.[1]||'';store.db.prepare('DELETE FROM sessions WHERE token=?').run(crypto.createHash('sha256').update(token).digest('hex'));res.setHeader('Set-Cookie','marala_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');return json(res,{ok:true});}
   if(p==='/api/lookups'&&method==='GET'){const allowed=MODULES.some(m=>store.can(user,m,'create')||store.can(user,m,'edit')||store.can(user,m,'view'));if(!allowed)fail('Akses ditolak.',403);return json(res,{units:store.list('units').map(({id,name})=>({id,name})),products:store.list('products').map(({id,name,code,unitId,unit,price})=>({id,name,code,unitId,unit,price})),customers:store.can(user,'invoices','view')||store.can(user,'customers','view')||store.can(user,'master','view')?store.list('customers'):[],banks:store.can(user,'invoices','create')||store.can(user,'settings','view')||store.can(user,'expenses','create')||store.can(user,'expenses','edit')?store.list('banks').filter(b=>b.active):[],stockitems:store.can(user,'stock','view')||store.can(user,'expenses','create')||store.can(user,'expenses','edit')?store.list('stockitems'):[],stocks:store.can(user,'stock','view')?store.list('stocks').map(s=>store.stockView(s)):[],invoices:store.can(user,'payments','view')||store.can(user,'expenses','view')?store.list('invoices').map(i=>{const v=store.invoiceView(i);return {id:v.id,number:v.number,customerName:v.customer.name,total:v.total,paid:v.paid,balance:v.balance};}):[]});}
   if(p==='/api/identity'&&method==='GET')return json(res,store.setting('identity'));
   if(p==='/api/settings'){gate(user,'settings',method==='GET'?'view':'edit');if(method==='GET')return json(res,{identity:store.setting('identity'),invoice:store.setting('invoice'),application:store.setting('application')});if(method==='POST'){const d=await body(req);store.tx(()=>{if(d.application){const a=d.application,name=String(a.name||'').trim(),shortName=String(a.shortName||name).trim();if(!name||name.length>80||!shortName||shortName.length>30)fail('Nama aplikasi wajib diisi (maksimal 80 karakter; nama singkat 30).');const previous=store.setting('application')||{};const icons={};for(const key of ['icon192','icon512']){const value=a[key]===undefined?(previous[key]||''):a[key];store.validateAttachment(value);if(value&&!/^data:image\/png;base64,/.test(value))fail('Ikon aplikasi harus PNG.');icons[key]=value;}if(Boolean(icons.icon192)!==Boolean(icons.icon512))fail('Kedua ukuran ikon wajib tersedia.');store.setSetting('application',{name,shortName,...icons,version:crypto.randomUUID()});}if(d.identity){const x=d.identity;if(!String(x.name||'').trim())fail('Nama BUMM wajib diisi.');store.validateAttachment(x.logo);if(x.logo&&!/^data:image\//.test(x.logo))fail('Logo harus gambar.');store.setSetting('identity',x);}if(d.invoice){if(!/^#[0-9a-f]{6}$/i.test(d.invoice.color))fail('Warna tidak valid.');if(!String(d.invoice.prefix||'').trim())fail('Prefix wajib diisi.');store.setSetting('invoice',d.invoice);}store.audit(user.id,'settings','update');});return json(res,{ok:true});}}
   const revealMatch=p.match(/^\/api\/users\/([^/]+)\/password$/);if(revealMatch&&method==='POST'){if(user.role!=='SUPER ADMIN')fail('Hanya Super Admin dapat melihat password.',403);return json(res,store.tx(()=>require('./password-vault.cjs').reveal(store,revealMatch[1],user.id)));}
   if(p==='/api/users'){gate(user,'users',method==='GET'?'view':'create');if(method==='GET')return json(res,store.db.prepare('SELECT id FROM users WHERE deleted=0').all().map(u=>({...store.user(u.id),...(user.role==='SUPER ADMIN'?{passwordAvailable:require('./password-vault.cjs').available(store,u.id)}:{})})));if(method==='POST'){const d=await body(req);return json(res,store.tx(()=>store.saveUser(d,null,user.id)),201);}}
   const userMatch=p.match(/^\/api\/users\/([^/]+)$/);if(userMatch){gate(user,'users',method==='DELETE'?'delete':'edit');const d=method==='DELETE'?null:await body(req);return json(res,store.tx(()=>{const old=store.user(userMatch[1]);if(!old)fail('Pengguna tidak ditemukan.',404);if(method==='DELETE'){store.saveUser({...old,active:false},old.id,user.id);store.db.prepare('UPDATE users SET deleted=1 WHERE id=?').run(old.id);require('./password-vault.cjs').remove(store,old.id);return {ok:true};}return store.saveUser(d,old.id,user.id);}));}
   if(p==='/api/legacy-seed'&&method==='GET'){if(user.role!=='SUPER ADMIN')fail('Hanya Super Admin.',403);if(!legacySeed)fail('Data contoh hanya tersedia di aplikasi lokal.',404);return json(res,legacySeed());}
   if(p==='/api/migrate'&&method==='POST'){gate(user,'settings','edit');if(user.role!=='SUPER ADMIN')fail('Migrasi hanya untuk Super Admin.',403);const d=await body(req);return json(res,store.tx(()=>migrate(store,d,user.id)));}
   if(p==='/api/backup'&&method==='GET'){if(user.role!=='SUPER ADMIN')fail('Hanya Super Admin dapat mencadangkan database.',403);if(f.full==='1')return json(res,require('./snapshot.cjs').exportSnapshot(store.db));return json(res,{version:1,records:store.db.prepare('SELECT * FROM records').all(),settings:store.db.prepare('SELECT * FROM settings').all(),imports:store.db.prepare('SELECT * FROM imports').all(),audit:store.db.prepare('SELECT * FROM audit').all()});}
   if(p==='/api/finance/settings'){
    gate(user,'reports','view');if(method==='GET')return json(res,{config:store.setting('finance')||{},plans:store.setting('assetPlans')||{},categories:require('./finance.cjs').CATEGORIES});
    if(method==='POST'){if(user.role!=='SUPER ADMIN')fail('Pengaturan laporan hanya untuk Super Admin.',403);const d=await body(req);return json(res,store.tx(()=>require('./finance.cjs').saveSettings(store,d,user.id)));}
   }
   const assetPlan=p.match(/^\/api\/finance\/asset\/([^/]+)$/);if(assetPlan&&method==='PUT'){if(user.role!=='SUPER ADMIN')fail('Pengaturan aset hanya untuk Super Admin.',403);const d=await body(req);return json(res,store.tx(()=>require('./finance.cjs').saveAsset(store,assetPlan[1],d,user.id)));}
   if(p==='/api/petty'&&method==='GET'){gate(user,'expenses','view');return json(res,store.petty(f.period||today().slice(0,7)));}
   if(p==='/api/report/opnames'&&method==='GET'){gate(user,'reports','view');const frozen=approvals.exact(store,f);return json(res,frozen?approvals.get(store,frozen.id).opnames:getRows('opnames',f));}
   if(p==='/api/report'&&method==='GET'){gate(user,'reports','view');const frozen=approvals.exact(store,f);return json(res,frozen?{...approvals.get(store,frozen.id).report,approval:frozen}:{...store.report(f),approval:null});}
   if(p==='/api/dashboard'&&method==='GET'){gate(user,'dashboard','view');const frozen=approvals.exact(store,f),r=frozen?approvals.get(store,frozen.id).report:store.dashboard(f);return json(res,{approval:frozen,revenue:r.revenue,outgoing:r.outgoing,cost:r.cost,tekoCost:r.tekoCost,otherCost:r.otherCost,profit:r.profit,stockValue:store.list('stocks').map(s=>store.stockView(s,f.to)).reduce((sum,s)=>sum+s.value,0),units:r.units,monthly:r.monthly,unpaid:store.can(user,'invoices','view')?store.list('invoices').map(i=>store.invoiceView(i)).filter(i=>i.balance>0):[],low:store.can(user,'stock','view')?store.list('stocks').map(s=>store.stockView(s)).filter(s=>['HABIS','STOK MINIMUM'].includes(s.status)):[]});}
   if(p==='/api/import/template'){gate(user,'expenses','create');const rows=[IMPORT_FIELDS,['',today(),'Operasional','Contoh pengeluaran',store.list('units')[0]?.name||'Nama unit bisnis',50000,'Cash','Petty Cash','Dibayar','']];res.writeHead(200,{'Content-Type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','Content-Disposition':'attachment; filename="Template_Pengeluaran.xlsx"'});return res.end(xlsx(rows));}
   if(p==='/api/import/preview'&&method==='POST'){gate(user,'expenses','create');return json(res,preview(await body(req)));}
   if(p==='/api/import/commit'&&method==='POST'){gate(user,'expenses','create');const d=await body(req);if(!Array.isArray(d.rows)||d.rows.length>2000||!d.rows.length)fail('Baris impor tidak valid.');const rows=store.tx(()=>d.rows.map((r,index)=>{try{return store.save('expenses',r,undefined,user.id);}catch(e){fail('Baris '+(index+1)+': '+(e.message.includes('UNIQUE')?'Nomor sudah digunakan.':e.message),e.status||(e.message.includes('UNIQUE')?409:400));}}));return json(res,{count:rows.length});}
   if(p==='/api/export'&&method==='GET'){const reportStock=f.kind==='opnamereport';const kind=reportStock?'opnames':f.kind;if(!GROUP[kind]&&!['profit','revenue'].includes(kind))fail('Laporan tidak dikenal.');gate(user,reportStock?'reports':GROUP[kind]||'reports','export');gate(user,reportStock?'reports':GROUP[kind]||'reports','view');const frozen=['profit','revenue','opnamereport'].includes(f.kind)?approvals.exact(store,f):null;if(frozen)return archiveExport(res,approvals.get(store,frozen.id),f);if(kind==='profit'&&f.format!=='csv'){const r=store.report(f),writer=require('./finance-export.cjs');res.writeHead(200,{'Content-Type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','Content-Disposition':'attachment; filename="Laba_Rugi_'+(f.from||'awal')+'_'+(f.to||'semua')+'.xlsx"','Cache-Control':'no-store'});return res.end(writer.workbook(writer.sheets(store,r,user)));}const rows=exportRows(kind,f),format=f.format==='csv'?'csv':'xlsx',name=`Laporan_${kind}_${f.from||'semua'}_${f.to||'semua'}.${format}`;res.writeHead(200,{'Content-Type':format==='xlsx'?'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':'text/csv; charset=utf-8','Content-Disposition':`attachment; filename="${name}"`,'Cache-Control':'no-store'});return res.end(format==='xlsx'?xlsx(rows):csv(rows));}
   const batch=p.match(/^\/api\/batch\/([a-z]+)$/);
   if(batch&&method==='POST'){
    const kind=batch[1];if((!GROUP[kind]&&kind!=='users')||kind==='stocks')fail('Modul input massal tidak tersedia.',404);
    gate(user,kind==='users'?'users':GROUP[kind],'create');const d=await body(req);
    if(!Array.isArray(d.rows)||!d.rows.length||d.rows.length>100)fail('Isi 1 sampai 100 baris.');
    const saved=store.tx(()=>d.rows.map((r,index)=>{try{
     if(!r||typeof r!=='object'||Array.isArray(r))fail('Data tidak valid.');
     if(kind==='requests'&&['Disetujui','Ditolak','Dicairkan','Selesai'].includes(r.status))gate(user,'requests','approve');
     return kind==='users'?store.saveUser(r,null,user.id):store.save(kind,r,undefined,user.id);
    }catch(e){fail('Baris '+(index+1)+': '+(e.message.includes('UNIQUE')?'Nomor atau username sudah digunakan.':e.message),e.status||(e.message.includes('UNIQUE')?409:400));}}));
    return json(res,{count:saved.length},201);
   }
   const match=p.match(/^\/api\/records\/([a-z]+)(?:\/([^/]+))?$/);if(match){const [,kind,id]=match;if(!GROUP[kind])fail('Modul tidak ditemukan.',404);const action=method==='GET'?'view':method==='POST'?'create':method==='PUT'?'edit':method==='DELETE'?'delete':null;if(!action)fail('Metode tidak didukung.',405);gate(user,GROUP[kind],action);if(method==='GET'){if(id)return json(res,kind==='invoices'?store.invoiceView(store.get(id,kind)):store.get(id,kind));return json(res,getRows(kind,f));}if(method==='DELETE')return json(res,store.tx(()=>{if(kind==='requests'&&['Disetujui','Ditolak','Dicairkan','Selesai'].includes(store.get(id,kind).status))gate(user,'requests','approve');store.remove(kind,id,user.id);return {ok:true};}));const d=await body(req);if(kind==='requests'){const old=id?store.get(id,kind):null;const protectedStatuses=['Disetujui','Ditolak','Dicairkan','Selesai'];if(protectedStatuses.includes(d.status)||protectedStatuses.includes(old?.status))gate(user,'requests','approve');}return json(res,store.tx(()=>store.save(kind,d,id,user.id)),method==='POST'?201:200);}
   fail('API tidak ditemukan.',404);
  }
  fail('API tidak ditemukan.',404);
 }catch(e){if(res.headersSent)return res.end();json(res,{error:e.message.includes('UNIQUE')?'Nomor atau username sudah digunakan.':e.status?e.message:'Terjadi kesalahan. Periksa data dan coba lagi.'},e.status||(/UNIQUE|FOREIGN KEY/.test(e.message)?409:500));if(!e.status&&!/UNIQUE/.test(e.message))console.error('API error:',e.message);}};
}
module.exports={createHandler};
