const {today,date,fail}=require('./domain.cjs');
function admin(user){if(user.role!=='SUPER ADMIN')fail('Hanya Super Admin dapat membuka pengaturan dan rekap absensi.',403);}
function own(s,userId){return s.db.prepare("SELECT data,id FROM records WHERE kind='attendance' AND deleted=0 AND json_extract(data,'$.userId')=? ORDER BY date DESC").all(userId).map(r=>({...JSON.parse(r.data),id:r.id}));}
function plans(s,userId){return s.db.prepare("SELECT data,id,rowid AS sequence,created_at FROM records WHERE kind IN ('attendanceschedules','attendanceplans') AND deleted=0"+(userId?" AND json_extract(data,'$.userId')=?":"")).all(...(userId?[userId]:[])).map(r=>({...JSON.parse(r.data),id:r.id,_sequence:r.sequence,createdDate:new Date(Date.parse(r.created_at)+7*3600000).toISOString().slice(0,10)})).sort((a,b)=>(b.effectiveFrom||b.createdDate).localeCompare(a.effectiveFrom||a.createdDate)||b._sequence-a._sequence);}
function resolve(all,id,day){const p=all.find(p=>p.userId===id&&(p.effectiveFrom||p.createdDate)<=day);if(!p)return null;const weekday=(new Date(day+'T12:00:00Z').getUTCDay()+6)%7;return {...p,...(p.week?p.week[weekday]:{off:false,start:p.start,end:p.end})};}
function schedule(s,id){return resolve(plans(s,id),id,today());}
function expected(day,p){const end=new Date(day+'T'+p.end+':00+07:00');if(p.end<p.start)end.setUTCDate(end.getUTCDate()+1);return {expectedIn:day+'T'+p.start+':00+07:00',expectedOut:end.toISOString()};}
function range(f={}){const from=f.from||today().slice(0,7)+'-01',to=f.to||today();date(from);date(to);if(from>to)fail('Rentang tanggal tidak valid.');if((Date.parse(to)-Date.parse(from))/86400000>365)fail('Pilih rentang maksimal 366 hari.');return {from,to};}
function calendar(actual,users,all,f){const {from,to}=range(f),rows=actual.filter(r=>r.date>=from&&r.date<=to).map(metrics),seen=new Set(rows.map(r=>r.userId+'/'+r.date));for(const u of users){for(let day=from;day<=to;day=new Date(Date.parse(day)+86400000).toISOString().slice(0,10)){if(seen.has(u.id+'/'+day))continue;const p=resolve(all,u.id,day);if(!p?.enabled)continue;const timing=p.off?{}:expected(day,p);rows.push({userId:u.id,name:u.name,username:u.username,date:day,virtual:true,status:p.off?'Libur':day>today()?'Belum berlangsung':Date.now()>Date.parse(timing.expectedOut)?'Tidak ada absensi':'Belum absen',scheduleStart:p.off?null:p.start,scheduleEnd:p.off?null:p.end,...timing,late:null,early:null,extra:null,duration:null});}}return rows.sort((a,b)=>b.date.localeCompare(a.date)||a.username.localeCompare(b.username));}
function metrics(r){const minutes=(a,b)=>Math.max(0,Math.floor((Date.parse(a)-Date.parse(b))/60000));return {...r,status:r.outAt?'Selesai':'Belum absen pulang',late:minutes(r.inAt,r.expectedIn),early:r.outAt?minutes(r.expectedOut,r.outAt):null,extra:r.outAt?minutes(r.outAt,r.expectedOut):null,duration:r.outAt?minutes(r.outAt,r.inAt):null};}
function view(s,user,f={}){const all=own(s,user.id),p=plans(s,user.id);return {today:today(),serverNow:new Date().toISOString(),completedToday:all.some(r=>r.date===today()&&r.outAt),schedule:resolve(p,user.id,today()),open:all.find(r=>!r.outAt)||null,rows:calendar(all,[user],p,f)};}
function punch(s,user,action){return s.tx(()=>{const all=own(s,user.id),open=all.find(r=>!r.outAt),dt=today(),at=new Date().toISOString();
 if(action==='out'){if(!open)fail('Belum ada absen masuk yang belum ditutup.');const result=s.put('attendance',{...open,outAt:at},open.id);s.audit(user.id,'attendance-out','attendance:'+result.id);return metrics(result);}
 if(action!=='in')fail('Tindakan absensi tidak valid.');if(open)fail('Masih ada absen masuk yang belum ditutup. Absen pulang dahulu.');if(all.some(r=>r.date===dt))fail('Absen hari ini sudah tercatat.');
 const plan=schedule(s,user.id);if(!plan?.enabled)fail('Jadwal belum diaktifkan. Hubungi Super Admin.');if(plan.off)fail('Hari ini libur sesuai jadwal. Hubungi Super Admin jika jadwal perlu diubah.');const timing=expected(dt,plan);
 const result=s.put('attendance',{number:'ATT/'+user.id+'/'+dt,userId:user.id,username:user.username,name:user.name,date:dt,inAt:at,...timing,scheduleVersionId:plan.id,scheduleStart:plan.start,scheduleEnd:plan.end});s.audit(user.id,'attendance-in','attendance:'+result.id);return metrics(result);
});}
function settings(s,user){admin(user);return {users:s.db.prepare('SELECT id,name,username,active FROM users WHERE deleted=0 ORDER BY name').all(),schedules:plans(s)};}
function saveSchedule(s,user,d){admin(user);return s.tx(()=>{const target=s.user(d.userId);if(!target)fail('User tidak ditemukan.');const effectiveFrom=d.effectiveFrom||today();date(effectiveFrom);if(effectiveFrom<today())fail('Jadwal baru tidak dapat berlaku sebelum hari ini.');const input=d.week??Array.from({length:7},()=>({off:false,start:d.start,end:d.end}));if(!Array.isArray(input)||input.length!==7)fail('Isi jadwal Senin sampai Minggu.');const week=input.map(day=>{if(!day||typeof day.off!=='boolean')fail('Pilih Masuk atau Libur untuk setiap hari.');if(day.off)return {off:true};for(const key of ['start','end'])if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(day[key]||''))fail('Isi jam masuk dan pulang yang valid.');if(day.start===day.end)fail('Jam masuk dan pulang harus berbeda.');return {off:false,start:day.start,end:day.end};});const r=s.put('attendanceplans',{userId:target.id,date:effectiveFrom,effectiveFrom,week,enabled:d.enabled===true});s.audit(user.id,'attendance-schedule','attendanceplans:'+r.id);return r;});}
function recap(s,user,f={}){admin(user);const period=range(f),users=s.db.prepare('SELECT id,name,username FROM users WHERE deleted=0').all().filter(u=>!f.userId||u.id===f.userId);return calendar(s.list('attendance',period).filter(r=>!f.userId||r.userId===f.userId),users,plans(s,f.userId),period);}
function overtime(s,user,d){admin(user);return s.tx(()=>{const r=s.get(d.id,'attendance');if(!r.outAt)fail('User belum absen pulang.');const extra=metrics(r).extra,minutes=Number(d.minutes);if(!Number.isInteger(minutes)||minutes<0||minutes>extra)fail('Menit lembur disetujui harus 0 sampai '+extra+'.');const saved=s.put('attendance',{...r,overtimeMinutes:minutes,overtimeNote:String(d.notes||'').trim().slice(0,500),reviewedBy:user.username,reviewedAt:new Date().toISOString()},r.id);s.audit(user.id,'attendance-overtime','attendance:'+r.id);return metrics(saved);});}
module.exports={view,punch,settings,saveSchedule,recap,overtime};
