const attendance=require('./attendance.cjs');
function sheets(store,user,filters){
 const rows=attendance.recap(store,user,filters).sort((a,b)=>a.username.localeCompare(b.username)||a.date.localeCompare(b.date));
 const time=v=>v?new Date(v).toLocaleString('id-ID',{timeZone:'Asia/Jakarta',hour12:false}):'';
 const scope=(filters.from||'Awal')+' s.d. '+(filters.to||'Semua tanggal');
 const groups=new Map();for(const r of rows){let g=groups.get(r.userId);if(!g){g={name:r.name,username:r.username,count:0,open:0,duration:0,late:0,early:0,extra:0,approved:0,unreviewed:0,holidays:0,missing:0};groups.set(r.userId,g);}if(r.virtual){if(r.status==='Libur')g.holidays++;if(r.status==='Tidak ada absensi')g.missing++;}else{g.count++;if(!r.outAt)g.open++;}g.duration+=r.duration||0;g.late+=r.late||0;g.early+=r.early||0;g.extra+=r.extra||0;g.approved+=r.overtimeMinutes||0;if(r.outAt&&r.overtimeMinutes===undefined)g.unreviewed++;}
 const make=(name,headers,data,widths,note)=>({name,header:4,merges:[1,2,3],filter:true,widths,rows:[[name+' — '+(store.setting('identity')?.name||'BUMM Marala')],[scope+' | '+(filters.userId?'User terpilih':'Semua user')],[note],headers,...data]});
 return [make('Ringkasan Absensi',['Nama','Username','Hari tercatat','Belum pulang','Durasi (menit)','Terlambat (menit)','Pulang awal (menit)','Lewat jadwal (menit)','Lembur disetujui (menit)','Belum ditinjau','Hari libur','Hari tanpa absensi'],[...groups.values()].map(g=>[g.name,g.username,g.count,g.open,g.duration,g.late,g.early,g.extra,g.approved,g.unreviewed,g.holidays,g.missing]),[26,20,16,16,20,20,20,20,24,18,16,22],'Bahan pengecekan gaji, bukan perhitungan upah. Durasi belum dikurangi istirahat. Lewat jadwal tidak otomatis lembur. Hari tercatat bukan jumlah hari wajib hadir.'),make('Rincian Absensi',['Tanggal masuk','Nama','Username','Jadwal masuk WIB','Jadwal pulang WIB','Masuk aktual WIB','Pulang aktual WIB','Status','Durasi (menit)','Terlambat (menit)','Pulang awal (menit)','Lewat jadwal (menit)','Lembur disetujui (menit)','Peninjauan','Catatan lembur','Ditinjau oleh','Waktu tinjau WIB'],rows.map(r=>[r.date,r.name,r.username,time(r.expectedIn),time(r.expectedOut),time(r.inAt),time(r.outAt),r.status,r.duration??'',r.late??'',r.early??'',r.extra??'',r.overtimeMinutes??'',r.virtual?'':r.overtimeMinutes===undefined?'Belum ditinjau':'Sudah ditinjau',r.overtimeNote||'',r.reviewedBy||'',time(r.reviewedAt)]),[16,26,20,25,25,25,25,24,20,20,20,20,24,20,40,20,25],'Tanggal mengikuti absen masuk, termasuk shift malam. Kolom kosong belum tersedia; angka 0 berarti nol. Filter mengikuti rekap yang ditampilkan.')];
}
module.exports={sheets};
