const crypto=require('node:crypto');
const MODULES=['masterchanges','pos','posmaster','posreports','posapproval','dashboard','master','customers','invoices','payments','sales','stock','expenses','requests','reports','settings','users'];
const ACTIONS=['view','create','edit','delete','approve','export'];
const GROUP={contacts:'customers',procurements:'expenses',referrals:'master',units:'master',products:'master',customers:'customers',invoices:'invoices',payments:'payments',sales:'sales',stockitems:'stock',transfers:'stock',stocks:'stock',movements:'stock',opnames:'stock',expenses:'expenses',requests:'requests',funds:'expenses',banks:'settings'};
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Jakarta'});
function fail(message,status=400){throw Object.assign(new Error(message),{status});}
function money(v,name='Nominal'){const n=Number(v);if(!Number.isSafeInteger(n)||n<0||n>1e12)fail(name+' harus berupa Rupiah bulat, antara 0 dan 1 triliun.');return n;}
function qty(v){const n=Number(v);if(!Number.isFinite(n)||n<0||n>1e9||Math.abs(Math.round(n*1000)-n*1000)>0.000001)fail('Jumlah harus positif dengan maksimal 3 angka desimal.');return n;}
function date(v){const d=new Date(v+'T00:00:00Z');if(!/^\d{4}-\d{2}-\d{2}$/.test(v||'')||!Number.isFinite(d.getTime())||d.toISOString().slice(0,10)!==v)fail('Tanggal tidak valid.');return v;}
function text(v,max=500){return String(v??'').trim().slice(0,max);}
function hash(password){if(typeof password!=='string'||password.length<10)fail('Password minimal 10 karakter.');const salt=crypto.randomBytes(16).toString('hex');return salt+':'+crypto.scryptSync(password,salt,64).toString('hex');}
function passwordOK(password,encoded){const [salt,key]=encoded.split(':');return crypto.timingSafeEqual(Buffer.from(key,'hex'),crypto.scryptSync(String(password),salt,64));}
function rolePermissions(role){return Object.fromEntries(MODULES.map(m=>[m,role==='SUPER ADMIN'?ACTIONS:role==='ADMIN'&&!['users','masterchanges'].includes(m)?ACTIONS:role==='STAFF'&&['pos','dashboard','invoices','payments','stock','expenses','customers'].includes(m)?['view','create','edit']:role==='VIEWER'&&!['settings','users'].includes(m)?['view']:[]]));}
class Store{
 constructor(db){this.db=db;this.db.exec(`
 CREATE TABLE IF NOT EXISTS schema_versions(version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS records(id TEXT PRIMARY KEY,kind TEXT NOT NULL,unit_id TEXT REFERENCES records(id),product_id TEXT REFERENCES records(id),invoice_id TEXT REFERENCES records(id),date TEXT,number TEXT,data TEXT NOT NULL,deleted INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
 CREATE UNIQUE INDEX IF NOT EXISTS unique_number ON records(kind,number) WHERE number IS NOT NULL;
 CREATE INDEX IF NOT EXISTS by_period ON records(kind,date,deleted);
 CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,username TEXT UNIQUE NOT NULL,name TEXT NOT NULL,password TEXT NOT NULL,role TEXT NOT NULL,permissions TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1,deleted INTEGER NOT NULL DEFAULT 0);
 CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),expires INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS audit(id INTEGER PRIMARY KEY,actor TEXT,action TEXT,entity TEXT,at TEXT NOT NULL);
 CREATE INDEX IF NOT EXISTS audit_by_entity ON audit(entity,id);
 CREATE INDEX IF NOT EXISTS records_by_invoice ON records(kind,invoice_id,deleted);
 CREATE INDEX IF NOT EXISTS records_active_period ON records(kind,deleted,date,created_at);
 CREATE INDEX IF NOT EXISTS records_active_unit ON records(kind,unit_id,deleted,date);
 CREATE INDEX IF NOT EXISTS attendance_user ON records(kind,deleted,json_extract(data,'$.userId'),date);
 CREATE TABLE IF NOT EXISTS imports(digest TEXT PRIMARY KEY,payload TEXT NOT NULL,at TEXT NOT NULL);
 CREATE TRIGGER IF NOT EXISTS immutable_reports_update BEFORE UPDATE ON records WHEN OLD.kind='reportarchives' BEGIN SELECT RAISE(ABORT,'Approved report is immutable'); END;
 CREATE TRIGGER IF NOT EXISTS immutable_reports_delete BEFORE DELETE ON records WHEN OLD.kind='reportarchives' BEGIN SELECT RAISE(ABORT,'Approved report is immutable'); END;
 CREATE TRIGGER IF NOT EXISTS immutable_reportparts_update BEFORE UPDATE ON records WHEN OLD.kind='reportarchiveparts' BEGIN SELECT RAISE(ABORT,'Approved report part is immutable'); END;
 CREATE TRIGGER IF NOT EXISTS immutable_reportparts_delete BEFORE DELETE ON records WHEN OLD.kind='reportarchiveparts' BEGIN SELECT RAISE(ABORT,'Approved report part is immutable'); END;
 INSERT OR IGNORE INTO schema_versions VALUES(1,datetime('now'));`);
 if(!this.setting('identity'))this.setSetting('identity',{name:'BUMM Marala',organization:'',address:'',phone:'',email:'',website:'',logo:''});
 if(!this.setting('invoice'))this.setSetting('invoice',{prefix:'INV/MARALA',showLogo:true,showAddress:true,showPhone:true,showBank:true,showNotes:true,showDiscount:true,showOther:true,showSignature:false,showFooter:true,showStatus:true,showPayments:false,footer:'Terima kasih telah mempercayakan layanan kepada BUMM Marala.',color:'#0b4ea2'});
 if(!this.db.prepare('SELECT version FROM schema_versions WHERE version=2').get())this.tx(()=>{require('./inventory.cjs').normalize(this);this.db.exec("INSERT OR IGNORE INTO schema_versions VALUES(2,datetime('now'))");});
 }
 tx(fn){
  if(this.db.transactionSync)return this.db.transactionSync(fn);
  const name='sp_'+crypto.randomBytes(8).toString('hex');
  this.db.exec('SAVEPOINT '+name);
  try{const result=fn();this.db.exec('RELEASE '+name);return result;}
  catch(e){this.db.exec('ROLLBACK TO '+name+'; RELEASE '+name);throw e;}
 }
 preview(fn){const rollback={};let result;try{this.tx(()=>{result=fn();throw rollback;});}catch(e){if(e!==rollback)throw e;}return result;}
 audit(actor,action,entity){
 const at=new Date().toISOString(),account=actor?this.db.prepare('SELECT id,name,username FROM users WHERE id=?').get(actor):null;
 const who=account?{id:account.id,name:account.name,username:account.username}:{id:actor||'system',name:actor==='setup'?'Pengaturan awal':actor==='preview'?'Pratinjau':actor&&actor!=='system'?'Akun lama / tidak tersedia':'Sistem',username:''};
 const result=this.db.prepare('INSERT INTO audit(actor,action,entity,at) VALUES(?,?,?,?)').run(actor||'system',action,entity,at);
 const id=entity.includes(':')?entity.slice(entity.indexOf(':')+1):entity,row=this.db.prepare('SELECT * FROM records WHERE id=?').get(id);
 let target=action==='user-save'?(this.db.prepare('SELECT name FROM users WHERE id=?').get(entity)?.name||entity):entity,kind=row?.kind||(['settings','user-save','migration'].includes(action)?action:'system');
 if(row){const data=JSON.parse(row.data);target=data.number||data.name||data.description||data.customerName||data.date||entity;
 const trace=this.provenance({...data,id:row.id,kind:row.kind})._trace||{};const isCreate=['create','transfer','pos-sale','pos-product-create'].includes(action)||(action==='pos-submit'&&data.revision===1);
 if(isCreate&&!data._trace?.createdBy){trace.createdBy=who;trace.createdAt=at;}trace.updatedBy=who;trace.updatedAt=at;data._trace=trace;
 this.put(row.kind,data,id,true);
 }
 this.put('auditmeta',{number:'AUDIT/'+String(this.db.prepare('SELECT max(id) AS id FROM audit').get().id),date:new Date(at).toLocaleDateString('en-CA',{timeZone:'Asia/Jakarta'}),actor:who,action,entity,recordId:row?.id||null,kind,target,at});
 }
 activityEvents(){const meta=new Map(this.list('auditmeta').map(e=>[e.number,e]));return this.db.prepare('SELECT * FROM audit ORDER BY id DESC').all().map(e=>meta.get('AUDIT/'+e.id)||{...e,date:new Date(e.at).toLocaleDateString('en-CA',{timeZone:'Asia/Jakarta'}),actor:{id:e.actor,name:this.db.prepare('SELECT name FROM users WHERE id=?').get(e.actor)?.name||'Akun lama / tidak tersedia',username:''},target:(()=>{const id=e.entity.includes(':')?e.entity.slice(e.entity.indexOf(':')+1):e.entity;const row=this.db.prepare('SELECT data FROM records WHERE id=?').get(id);if(!row)return e.entity;const d=JSON.parse(row.data);return d.number||d.name||d.description||d.customerName||d.date||e.entity;})(),legacy:true});}
 provenance(record){if(!record)return record;let trace=record._trace;if(!trace){const events=this.db.prepare('SELECT * FROM audit WHERE entity=? OR entity=? ORDER BY id').all(record.id,(record.kind||'')+':'+record.id);const created=events.find(e=>['create','transfer','pos-sale','pos-product-create'].includes(e.action));const last=events.at(-1);const who=e=>{if(!e)return null;const u=this.db.prepare('SELECT id,name,username FROM users WHERE id=?').get(e.actor);return u?{...u,legacy:true}:{id:e.actor,name:'Akun lama / tidak tersedia',username:'',legacy:true};};trace={createdBy:who(created),createdAt:created?.at,updatedBy:who(last),updatedAt:last?.at};}return {...record,_trace:trace};}

 setting(key){const r=this.db.prepare('SELECT value FROM settings WHERE key=?').get(key);return r?JSON.parse(r.value):null;}
 setSetting(key,value){this.db.prepare('INSERT INTO settings VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').run(key,JSON.stringify(value));}
 get(id,kind,includeDeleted=false){const r=this.db.prepare('SELECT * FROM records WHERE id=?').get(id);if(!r||kind&&r.kind!==kind||r.deleted&&!includeDeleted)fail('Data tidak ditemukan.',404);return {...JSON.parse(r.data),id:r.id,deleted:!!r.deleted};}
 list(kind,f={}){let sql='SELECT data,id,rowid AS sequence FROM records WHERE kind=? AND deleted=0',args=[kind];if(f.from){date(f.from);sql+=' AND date>=?';args.push(f.from);}if(f.to){date(f.to);sql+=' AND date<=?';args.push(f.to);}if(f.from&&f.to&&f.from>f.to)fail('Tanggal mulai melebihi tanggal akhir.');if(f.unitId){sql+=' AND unit_id=?';args.push(f.unitId);}let rows=this.db.prepare(sql+' ORDER BY date DESC,created_at DESC,rowid DESC').all(...args).map(r=>({...JSON.parse(r.data),id:r.id,_sequence:r.sequence}));if(f.q&&kind!=='referrals'){const q=f.q.toLowerCase();rows=rows.filter(r=>JSON.stringify(r).toLowerCase().includes(q));}if(kind==='referrals'){rows=rows.map(r=>({...r,customerName:this.get(r.customerId,'customers').name}));if(f.customerId)rows=rows.filter(r=>r.customerId===f.customerId);if(f.marketing)rows=rows.filter(r=>r.marketing.toLowerCase().includes(f.marketing.toLowerCase()));if(f.q)rows=rows.filter(r=>JSON.stringify(r).toLowerCase().includes(f.q.toLowerCase()));}if(f.location)rows=rows.filter(r=>r.location===f.location);return rows;}
 put(kind,data,id=crypto.randomUUID(),trustedTrace=false){id=id||crypto.randomUUID();data={...data};const prior=this.db.prepare('SELECT data FROM records WHERE id=?').get(id);if(!trustedTrace)delete data._trace;if(prior&&!trustedTrace){const trace=JSON.parse(prior.data)._trace;if(trace)data._trace=trace;}const now=new Date().toISOString();this.db.prepare(`INSERT INTO records(id,kind,unit_id,product_id,invoice_id,date,number,data,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET unit_id=excluded.unit_id,product_id=excluded.product_id,invoice_id=excluded.invoice_id,date=excluded.date,number=excluded.number,data=excluded.data,updated_at=excluded.updated_at`).run(id,kind,data.unitId||null,data.productId||null,data.invoiceId||null,data.date||null,data.number||null,JSON.stringify(data),now,now);return {...data,id};}
 ref(id,kind){if(!id)fail('Pilihan '+kind+' wajib diisi.');return this.get(id,kind);}
 uniqueName(kind,name,id){if(this.list(kind).some(r=>r.id!==id&&r.name.toLowerCase()===name.toLowerCase()))fail('Nama sudah terdaftar.');}
 validateAttachment(v){v=text(v,3e6);if(v&&!/^data:(image\/(png|jpeg|webp)|application\/pdf);base64,[A-Za-z0-9+/=]+$/.test(v))fail('Lampiran harus PNG, JPEG, WebP, atau PDF, maksimal 2 MB.');return v;}
 save(kind,input,id,actor){if(kind==='contacts')return require('./contacts.cjs').save(this,input,id,actor);if(kind==='procurements')return require('./procurement.cjs').save(this,input,id,actor);if(kind==='stockitems')return require('./inventory.cjs').saveItem(this,input,id,actor);if(kind==='transfers'){if(id)fail('Transfer yang sudah dicatat tidak dapat diubah.');return require('./inventory.cjs').transfer(this,input,actor);}if(!GROUP[kind])fail('Jenis data tidak dikenal.');const old=id?this.get(id,kind):null;if(kind==='sales'&&old?.posDayId)fail('Ubah rekap kasir melalui revisi approval.',409);let d={...input};delete d.id;delete d.deleted;delete d._sequence;const required=(key,label=key)=>{d[key]=text(d[key]);if(!d[key])fail(label+' wajib diisi.');};
 if(['units','products','customers','stocks'].includes(kind))required('name','Nama');
 if(kind==='units'){this.uniqueName(kind,d.name,id);d={name:d.name,notes:text(d.notes)};}
 if(kind==='products'){this.ref(d.unitId,'units');required('code','Kode');if(this.list(kind).some(r=>r.id!==id&&r.code===d.code))fail('Kode produk sudah ada.');required('unit','Satuan');d.price=money(d.price);d.cost=money(d.cost);d.type=text(d.type)||'Produk';}
 if(kind==='referrals'){const customer=this.ref(d.customerId,'customers');d={customerId:customer.id,marketing:text(d.marketing),amount:money(d.amount),date:date(d.date),notes:text(d.notes)};if(!d.marketing)fail('Nama marketing wajib diisi.');}
 if(kind==='customers'){required('phone','Nomor telepon');this.uniqueName(kind,d.name,id);const normalize=require('./contacts.cjs').phone,key=normalize(d.phone);if(key&&(!old||normalize(old.phone)!==key)&&this.list('customers').some(r=>r.id!==id&&normalize(r.phone)===key))fail('Nomor telepon sudah terdaftar pada customer lain.',409);}
 if(['invoices','sales','payments','movements','opnames','expenses','requests','funds'].includes(kind))d.date=date(d.date);
 if(['sales','expenses','requests'].includes(kind))this.ref(d.unitId,'units');
 if(kind==='banks'){required('name','Nama bank');required('account','Nomor rekening');required('owner','Pemilik rekening');d.active=d.active!==false;}
 if(kind==='invoices'){
  this.ref(d.unitId,'units');const customer=this.ref(d.customerId,'customers');d.customer={name:customer.name,phone:customer.phone,notes:customer.notes};d.dueDate=date(d.dueDate);if(d.dueDate<d.date)fail('Jatuh tempo sebelum tanggal invoice.');
  if(!Array.isArray(d.items)||!d.items.length||d.items.length>100)fail('Isi minimal satu item invoice.');
  d.items=d.items.map(item=>{const p=old?.items?.some(i=>i.productId===item.productId)?this.get(item.productId,'products',true):this.ref(item.productId,'products');if(p.unitId!==d.unitId)fail('Produk harus berasal dari unit invoice.');const name=text(item.name),unit=text(item.unit);if(!name||!unit)fail('Nama dan satuan item wajib diisi.');const quantity=qty(item.qty);if(!quantity)fail('Jumlah item harus lebih dari nol.');const price=money(item.price),discount=money(item.discount||0),gross=Math.round(quantity*price);money(gross);if(discount>gross)fail('Diskon item melebihi harga item.');return {productId:p.id,name,unit,qty:quantity,price,cost:p.cost,discount,notes:text(item.notes),subtotal:gross-discount};});
  d.subtotal=money(d.items.reduce((s,i)=>s+Math.round(i.qty*i.price),0));d.discount=money(d.discount||0);d.itemDiscount=d.items.reduce((s,i)=>s+i.discount,0);d.other=money(d.other||0);if(d.discount+d.itemDiscount>d.subtotal)fail('Diskon melebihi total harga.');d.total=money(d.subtotal-d.discount-d.itemDiscount+d.other);
  if(old&&this.paid(id)>d.total)fail('Total tidak boleh lebih kecil dari pembayaran yang diterima.');
  d.number=old?.number||text(d.number)||this.nextNumber('invoices',this.setting('invoice').prefix,d.date);d.identity=old?.identity||this.setting('identity');d.options=old?.options||this.setting('invoice');d.bank=old&&d.bankId===old.bankId?old.bank:(d.bankId?this.ref(d.bankId,'banks'):null);if(d.bank&&(!old||d.bankId!==old.bankId)&&!d.bank.active)fail('Rekening tidak aktif.');if(['Sewa Ruangan','Vendor'].includes(this.get(d.unitId,'units').name)&&(!d.eventDate||!d.eventStart||!d.eventEnd))fail('Tanggal dan jam acara wajib untuk unit sewa ruangan/vendor.');if(d.eventDate)date(d.eventDate);for(const time of [d.eventStart,d.eventEnd])if(time&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(time))fail('Jam acara tidak valid.');if(d.eventStart&&d.eventEnd&&d.eventEnd<=d.eventStart)fail('Jam selesai harus setelah jam mulai.');
 }
 if(kind==='payments'){const invoice=this.ref(d.invoiceId,'invoices');d.amount=money(d.amount);if(!d.amount||d.amount>invoice.total-this.paid(invoice.id)+(old?.amount||0))fail('Pembayaran harus positif dan tidak melebihi sisa tagihan.');required('method','Metode');d.customerName=invoice.customer.name;}
 if(['sales','expenses'].includes(kind))require('./finance.cjs').validateDetails(this,kind,d,id);
 if(kind==='sales'){d.amount=money(d.amount);if(d.productId){const p=old?.productId===d.productId?this.get(d.productId,'products',true):this.ref(d.productId,'products');if(p.unitId!==d.unitId)fail('Unit produk berbeda.');d.productName=p.name;}required('description','Deskripsi');d.number=old?.number||text(d.number)||this.nextNumber(kind,'JUAL',d.date);d.cost=money(d.cost||0);}
 if(kind==='stocks')fail('Kelola barang melalui Master Stok Gudang.');
 if(kind==='movements'){delete d.posDayId;delete d.procurementId;delete d.acquisitionValue;}
 if(kind==='movements'||kind==='opnames'){if(old)fail('Riwayat stok tidak dapat diubah; buat transaksi koreksi.');const stock=this.ref(d.stockId,'stocks');if(d.location&&d.location!==stock.location)fail('Barang tidak sesuai lokasi yang dipilih.');delete d.unitId;delete d.productId;d.location=stock.location;d.unit=stock.unit;d.name=stock.name;d.price=stock.stockItemId?this.get(stock.stockItemId,'stockitems',true).price:money(d.price??stock.price);const before=this.stockQuantity(stock.id,d.date);if(kind==='movements'){if(!['Masuk','Keluar'].includes(d.direction))fail('Jenis mutasi tidak valid.');d.quantity=qty(d.quantity);if(!d.quantity)fail('Jumlah mutasi harus lebih dari nol.');d.delta=d.direction==='Masuk'?d.quantity:-d.quantity;}else{d.system=before;d.actual=qty(d.actual);d.delta=Math.round((d.actual-before)*1000)/1000;d.difference=d.delta;d.differenceValue=Math.round(d.delta*d.price);}if(before+d.delta<0)fail('Stok tidak cukup.');let balance=0;const timeline=[...['movements','opnames'].flatMap(k=>this.list(k)).filter(m=>m.stockId===stock.id),{...d,_sequence:Number.MAX_SAFE_INTEGER}].sort((a,b)=>a.date.localeCompare(b.date)||a._sequence-b._sequence);for(const m of timeline){balance+=m.delta;if(balance<0)fail('Tanggal transaksi menyebabkan saldo stok historis negatif.');}}
 if(kind==='expenses'){d.number=old?.number||text(d.number)||this.nextNumber('expenses','EXP',d.date);required('category','Kategori');required('description','Deskripsi');d.amount=money(d.amount);if(!d.amount)fail('Nominal harus lebih dari nol.');if(!['Petty Cash','Rekening','Lainnya'].includes(d.source))fail('Sumber dana tidak valid.');required('method','Metode');if(!['Draft','Dibayar','Dibatalkan'].includes(d.status))fail('Status pengeluaran tidak valid.');d.proof=this.validateAttachment(d.proof);}
 if(kind==='requests'){required('number','Nomor pengajuan');required('letterNumber','Nomor surat');required('applicant','Pengaju');required('description','Keperluan');d.amount=money(d.amount);if(!['Draft','Diajukan','Disetujui','Ditolak','Dicairkan','Selesai'].includes(d.status))fail('Status pengajuan tidak valid.');d.proof=this.validateAttachment(d.proof);}
 if(kind==='funds'){d.amount=money(d.amount);if(!d.amount)fail('Dana masuk harus lebih dari nol.');required('description','Keterangan');}
 if(['expenses','funds'].includes(kind))require('./finance.cjs').validateCashChange(this,kind,d,id);
 const saved=this.put(kind,d,id);if(['movements','opnames'].includes(kind)){const stock=this.get(d.stockId,'stocks');const latest=['movements','opnames'].flatMap(k=>this.list(k)).filter(m=>m.stockId===stock.id).sort((a,b)=>a.date.localeCompare(b.date)||a._sequence-b._sequence).at(-1);this.put('stocks',{...stock,price:latest.price},stock.id);}this.audit(actor,old?'edit':'create',kind+':'+saved.id);return saved;
 }
 nextNumber(kind,prefix,dt){const count=this.db.prepare('SELECT count(*) n FROM records WHERE kind=?').get(kind).n+1;let n=count;while(this.db.prepare('SELECT id FROM records WHERE kind=? AND number=?').get(kind,`${prefix}/${dt.slice(0,4)}/${String(n).padStart(5,'0')}`))n++;return `${prefix}/${dt.slice(0,4)}/${String(n).padStart(5,'0')}`;}
 paid(id){return this.db.prepare("SELECT data FROM records WHERE kind='payments' AND invoice_id=? AND deleted=0").all(id).reduce((s,r)=>s+JSON.parse(r.data).amount,0);}
 invoiceView(i){const paid=this.paid(i.id);return {...i,paid,balance:Math.max(0,i.total-paid),status:paid>=i.total?'Lunas':paid?'Sebagian Dibayar':'Menunggu Pembayaran'};}
 stockQuantity(id,to){return Math.round(['movements','opnames'].flatMap(k=>this.list(k,to?{to}:{})).filter(m=>m.stockId===id).reduce((s,m)=>s+m.delta,0)*1000)/1000;}
 stockView(s,to){const quantity=this.stockQuantity(s.id,to),history=['movements','opnames'].flatMap(k=>this.list(k,to?{to}:{})).filter(m=>m.stockId===s.id).sort((a,b)=>a.date.localeCompare(b.date)||a._sequence-b._sequence);const price=s.stockItemId?this.get(s.stockItemId,'stockitems',true).price:(to?(history.at(-1)?.price??s.price):s.price);let value=Math.round(quantity*price),valuedPrice=price;if(history.some(m=>m.acquisitionValue!==undefined)){let q=0,v=0;for(const m of history){if(m.delta>0)v+=m.acquisitionValue??Math.round(m.delta*(q?v/q:price));else if(m.delta<0)v+=m.delta*(q?v/q:price);q=Math.round((q+m.delta)*1000)/1000;if(!q)v=0;}value=Math.round(v);valuedPrice=quantity?value/quantity:price;}return {...s,price:valuedPrice,quantity,value,status:quantity===0?'HABIS':quantity<s.min?'STOK MINIMUM':quantity>s.max?'STOK BERLEBIH':'NORMAL'};}
 petty(period){return require('./finance.cjs').petty(this,period);}
 remove(kind,id,actor){const row=this.get(id,kind);if(kind==='procurements')return require('./procurement.cjs').remove(this,id,actor);if(kind==='sales'&&row.posDayId)fail('Buka revisi approval kasir untuk mengubah rekap.',409);if(['movements','opnames','transfers','stocks'].includes(kind))fail('Riwayat stok dipertahankan; gunakan mutasi koreksi.');if(kind==='invoices'&&this.paid(id)>0)fail('Invoice memiliki pembayaran; batalkan pembayaran terlebih dahulu.');if(['units','customers','stocks','banks'].includes(kind)){const refs=this.db.prepare('SELECT data FROM records WHERE deleted=0 AND id<>?').all(id);if(refs.some(r=>{const d=JSON.parse(r.data);return [d.unitId,d.productId,d.customerId,d.stockId,d.bankId].includes(id)||(d.items||[]).some(i=>i.productId===id);}))fail('Data masih digunakan transaksi atau master lain.');}if(kind==='funds')require('./finance.cjs').validateCashChange(this,kind,null,id);this.db.prepare('UPDATE records SET deleted=1,updated_at=? WHERE id=?').run(new Date().toISOString(),id);this.audit(actor,'delete',kind+':'+id);}
 report(f={}){return require('./finance.cjs').report(this,f);}
 dashboard(f={}){return this.report(f);}

 user(id){const u=this.db.prepare('SELECT * FROM users WHERE id=? AND deleted=0').get(id);if(!u)return null;delete u.password;u.permissions=JSON.parse(u.permissions);return u;}
 can(user,module,action){if(user?.role!=='SUPER ADMIN'&&['master','posmaster'].includes(module)&&['create','edit','delete'].includes(action)&&!user?.permissions?.masterchanges?.includes(action))return false;return !!user?.active&&(user.role==='SUPER ADMIN'||user.permissions[module]?.includes(action));}
 saveUser(d,id,actor){const old=id?this.user(id):null;if(id&&!old)fail('Pengguna tidak ditemukan.');const username=text(d.username,80).toLowerCase(),name=text(d.name,100);if(!/^[a-z0-9._-]{3,80}$/.test(username)||!name)fail('Username minimal 3 karakter huruf/angka dan nama wajib diisi.');if(!['SUPER ADMIN','ADMIN','STAFF','VIEWER'].includes(d.role))fail('Role tidak valid.');const active=d.active!==false;if(old?.role==='SUPER ADMIN'&&old.active&&(!active||d.role!=='SUPER ADMIN')&&this.db.prepare("SELECT count(*) n FROM users WHERE role='SUPER ADMIN' AND active=1 AND deleted=0").get().n<=1)fail('Minimal satu Super Admin harus aktif.');const permissions=d.permissions||rolePermissions(d.role);const operator=actor?this.user(actor):null;if(operator&&operator.role!=='SUPER ADMIN'&&(d.role==='SUPER ADMIN'||JSON.stringify(permissions.masterchanges||[])!==JSON.stringify(old?.permissions?.masterchanges||[])))fail('Hanya Super Admin dapat memberi akses perubahan master atau role Super Admin.',403);for(const [m,a]of Object.entries(permissions))if(!MODULES.includes(m)||!Array.isArray(a)||a.some(x=>!ACTIONS.includes(x)))fail('Permission tidak valid.');const password=d.password?hash(d.password):old?this.db.prepare('SELECT password FROM users WHERE id=?').get(id).password:hash('');id=id||crypto.randomUUID();this.db.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,?,0) ON CONFLICT(id) DO UPDATE SET username=excluded.username,name=excluded.name,password=excluded.password,role=excluded.role,permissions=excluded.permissions,active=excluded.active').run(id,username,name,password,d.role,JSON.stringify(permissions),Number(active));if(d.password)require('./password-vault.cjs').save(this,id,d.password);this.db.prepare('DELETE FROM sessions WHERE user_id=?').run(id);this.audit(actor,'user-save',id);return this.user(id);}
}
module.exports={Store,MODULES,ACTIONS,GROUP,rolePermissions,passwordOK,today,money,date,fail};
