const {zip,xml,column}=require('./workbook.cjs');
const {cashRows}=require('./finance.cjs');
const sum=(rows,key)=>rows.reduce((n,r)=>n+Number(r[key]||0),0);
const num=v=>({value:v,style:3});
const criterion=v=>v.replace(/~/g,'~~').replace(/\*/g,'~*').replace(/\?/g,'~?').replace(/"/g,'""');
const dt=v=>v?({value:Math.round((Date.parse(v+'T00:00:00Z')-Date.UTC(1899,11,30))/86400000),style:5}):'';
const formula=(formula,value,style=3)=>({formula,value,style});
function sheets(s,r,user){
 const company=s.setting('identity')?.name||'BUMM Marala',period=(r.from||'Awal pencatatan')+' s.d. '+(r.to||'Seluruh data'),scope=s.list('units').find(u=>u.id===r.unitId)?.name||'Semua unit bisnis';
 const stamp=new Date().toLocaleString('id-ID',{timeZone:'Asia/Jakarta'})+' WIB';
 const make=(name,headers,rows,widths,note='')=>({name,rows:[[company+' — '+name],[period+' | '+scope],[note||'Sumber: transaksi tersimpan di aplikasi. Nilai dalam Rupiah.'],headers,...rows],widths,header:4,merges:[1,2,3],filter:true});
 const income=make('Pendapatan',['Tanggal masuk','Nomor referensi','Sumber','Unit bisnis','Keterangan','Omzet (Rp)','HPP tercatat (Rp)','Tanggal invoice'],r.entries.map(e=>[dt(e.date),e.number,e.source,e.unitName,e.description,num(e.amount),num(e.cost),dt(e.invoiceDate)]),[15,30,27,24,45,21,22,17],'DP/pelunasan sesuai tanggal pembayaran. HPP invoice dibagi proporsional; rekap kasir hanya yang disetujui.');
 const costs=make('Biaya',['Tanggal bayar','Nomor','Kategori','Unit bisnis','Kelompok','Keterangan','Invoice terkait','Nominal (Rp)'],r.expenses.map(e=>[dt(e.date),e.number,e.category,e.unitName,e.costClass,e.description,e.invoiceNumber,num(e.amount)]),[15,23,21,21,22,34,25,20],'HPP = biaya langsung tambahan. Tercakup HPP invoice tidak dikurangi lagi. Rincian satuan dan penerima ada di Detail Biaya.');
 const detailCosts=make('Detail Biaya',['Nomor','Keterangan','Penerima','Periode gaji','Jumlah','Satuan','Harga satuan (Rp)','Nominal (Rp)','Sumber dana'],r.expenses.map(e=>[e.number,e.description,e.recipient||'',e.payPeriod||'',e.quantity??'',e.unit||'',e.unitPrice===undefined?'':num(e.unitPrice),num(e.amount),e.source]),[23,32,24,16,12,12,20,20,18],'Rincian pendukung transaksi pada Biaya. Nominal di sini tidak ditambahkan lagi ke laba rugi.');
 const dep=make('Penyusutan',['Tanggal pengakuan','Nomor aset','Aset','Unit bisnis','Beban (Rp)'],r.depreciationRows.map(e=>[dt(e.date),e.number,e.description,e.unitName,num(e.amount)]),[20,28,42,24,23],'Metode garis lurus. Satu bulan penuh diakui pada akhir bulan, mulai bulan yang ditetapkan.');
 const assets=make('Aset',['Nomor','Tanggal beli','Aset / unit bisnis','Perolehan (Rp)','Manfaat (bulan)','Mulai susut','Nilai sisa (Rp)','Akumulasi (Rp)','Nilai buku (Rp)'],r.assets.map(a=>[a.number,dt(a.date),a.name+' / '+a.unitName,num(a.amount),a.plan?.life??'Belum diatur',a.plan?.start||'',a.plan?num(a.plan.residual):'',num(a.accumulated),num(a.bookValue)]),[24,15,30,19,16,14,19,19,19],'Pembelian aset tidak dikurangi langsung dari laba. Aset tanpa pengaturan belum menyumbang beban penyusutan.');
 const endI=Math.max(5,income.rows.length),endC=Math.max(5,costs.rows.length),endD=Math.max(5,dep.rows.length);
 const summary={name:'Laba Rugi',widths:[36,23,13,30],header:7,merges:[1,2,3,4,5,6],rows:[[company],['LAPORAN LABA RUGI MANAJEMEN'],[period+' | '+scope],['Uang masuk + HPP terkait + biaya dibayar + penyusutan non-tunai'],['Dicetak '+stamp+' oleh '+user.name],[(r.query?'Pencarian aktif: '+r.query+'. ':'')+(r.warnings.length?r.warnings.length+' catatan perlu ditinjau pada lembar Catatan.':'Tidak ada peringatan otomatis. Tetap cocokkan kelengkapan transaksi.')],['Uraian','Nominal (Rp)','Margin','Keterangan']]};
 const out=summary.rows,totals=[],add=(label,value,note='',style=3)=>{out.push([label,typeof value==='object'?value:{value,style},'',note]);return out.length;};
 out.push(['PENDAPATAN']);const incStart=out.length+1;
 for(const u of r.units.filter(u=>!r.unitId||u.id===r.unitId)){const escaped=criterion(u.name);add(u.name,formula(`SUMIFS(Pendapatan!F5:F${endI},Pendapatan!D5:D${endI},"${escaped}")`,u.revenue),u.group!==u.name?'Kelompok: '+u.group:'');}
 const incEnd=out.length,rev=add('TOTAL PENDAPATAN',formula(incEnd>=incStart?`SUM(B${incStart}:B${incEnd})`:'0',r.revenue,6));totals.push(rev);
 out.push(['HARGA POKOK PENJUALAN']);const costStart=out.length+1;
 for(const u of r.units.filter(u=>!r.unitId||u.id===r.unitId)){const escaped=criterion(u.name);add('HPP '+u.name,formula(`SUMIFS(Pendapatan!G5:G${endI},Pendapatan!D5:D${endI},"${escaped}")+SUMIFS(Biaya!H5:H${endC},Biaya!D5:D${endC},"${escaped}",Biaya!E5:E${endC},"HPP")`,u.cost));}
 const costEnd=out.length,cost=add('TOTAL HPP',formula(costEnd>=costStart?`SUM(B${costStart}:B${costEnd})`:'0',r.cost,6));totals.push(cost);
 const gross=add('LABA KOTOR',formula(`B${rev}-B${cost}`,r.grossProfit,6));out.at(-1)[2]=r.grossMargin===null?'Tidak tersedia':formula(`IF(B${rev}=0,"Tidak tersedia",B${gross}/B${rev})`,r.grossMargin,4);totals.push(gross);
 out.push(['BIAYA OPERASIONAL']);const opStart=out.length+1;
 for(const c of r.categories){if(c.name==='Penyusutan Aset (non-tunai)')add(c.name,formula(`SUM(Penyusutan!E5:E${endD})`,c.amount));else add(c.name,formula(`SUMIFS(Biaya!H5:H${endC},Biaya!C5:C${endC},"${criterion(c.name)}",Biaya!E5:E${endC},"Operasional")`,c.amount));}
 const opEnd=out.length,op=add('TOTAL BIAYA OPERASIONAL',formula(opEnd>=opStart?`SUM(B${opStart}:B${opEnd})`:'0',r.outgoing,6));totals.push(op);
 const net=add('LABA BERSIH',formula(`B${gross}-B${op}`,r.profit,6));out.at(-1)[2]=r.netMargin===null?'Tidak tersedia':formula(`IF(B${rev}=0,"Tidak tersedia",B${net}/B${rev})`,r.netMargin,4);totals.push(net);
 out.push([],['Disusun oleh',user.name,'Diperiksa oleh','________________'],['Tanggal pemeriksaan','','','________________']);summary.totals=totals;summary.filter=false;
 const liveCosts=require('./live-cost.cjs').calculator(s),scopeDates=new Set(r.entries.filter(e=>e.posDayId).map(e=>e.date+'~'+(s.get(e.posDayId,'posdays').batch||0))),approvedDates=new Set(s.list('sales').filter(e=>e.posDayId).map(e=>e.date+'~'+(s.get(e.posDayId,'posdays').batch||0))),tekoId=require('./pos.cjs').unit(s)?.id;
 const productRows=[];
 if(!r.unitId||r.unitId===tekoId)for(const t of s.list('postickets').filter(t=>t.status==='Selesai'&&(!r.query||scopeDates.has(t.date+'~'+(t.batch||0)))&&(!r.from||t.date>=r.from)&&(!r.to||t.date<=r.to))){for(const i of liveCosts.ticket(t).items)productRows.push([dt(t.date),new Date(t.date+'T00:00:00Z').toLocaleDateString('id-ID',{weekday:'long',timeZone:'UTC'}),t.number,i.name,i.qty,num(i.amount),num(i.hpp),approvedDates.has(t.date+'~'+(t.batch||0))?'Masuk omzet':'Belum masuk omzet']);}
 for(const e of r.entries.filter(e=>e.source==='Penjualan langsung'))productRows.push([dt(e.date),'',e.number,e.productName||e.description,e.quantity??'Tidak tersedia',num(e.amount),num(e.cost),'Penjualan langsung']);
 const products=make('Rincian Produk',['Tanggal','Hari','Nomor transaksi','Produk / keterangan','Jumlah','Penjualan (Rp)','HPP (Rp)','Status'],productRows,[16,16,30,42,20,22,22,25],'Rincian kasir setelah alokasi diskon transaksi, sesuai omzet pada Pendapatan. Data total lama tidak memiliki jumlah produk.');
 const all=cashRows(s),cfg=s.setting('finance')||{},start=cfg.pettyStart||(all[0]?.date.slice(0,7)||new Date().toISOString().slice(0,7))+'-01',from=r.from||start,to=r.to||'9999-12-31';let running=(start<=from?(cfg.pettyOpening??1000000):0)+sum(all.filter(e=>e.date>=start&&e.date<from),'delta');const cash=[[dt(from),'Saldo awal periode','','',num(running),'Seluruh unit']];
 for(const e of all.filter(e=>e.date>=start&&e.date>=from&&e.date<=to)){running+=e.delta;cash.push([dt(e.date),e.description,e.delta>0?num(e.delta):'',e.delta<0?num(-e.delta):'',num(running),s.list('units').find(u=>u.id===e.unitId)?.name||'Dana umum']);}
 const pettySheet=make('Petty Cash',['Tanggal','Keterangan','Masuk (Rp)','Keluar (Rp)','Saldo (Rp)','Unit bisnis'],cash,[16, 50,22,22,22,25],'Buku kas SELURUH UNIT; filter unit/pencarian tidak berlaku di sini. Sumber dana bukan pengurang laba tambahan.');
 const notes=make('Catatan',['Referensi','Tanggal','Penjelasan'],[['Dasar laporan','','Laporan manajemen sesuai uang masuk. Bukan laba berbasis tanggal invoice.'],['HPP invoice','','Dialokasikan menurut proporsi pembayaran. Pembulatan kumulatif memastikan total HPP tidak berganda.'],['Biaya','','Biaya dibayar mengikuti tanggal pengeluaran. Biaya tercakup HPP invoice tidak dikurangi lagi.'],['Aset','','Pengadaan aset/persediaan tidak langsung menjadi beban. Penyusutan diakui pada akhir bulan.'],['Kelengkapan','','Angka mengikuti transaksi tercatat. HPP nol atau data belum lengkap dapat menyebabkan laba terlalu tinggi.'],['Kasir','','Hanya rekap harian disetujui masuk omzet. Rincian Produk memisahkan transaksi yang belum masuk.'],['Pencarian','',r.query||'Tidak ada filter pencarian'],...r.warnings.map(w=>[w.number,dt(w.date),w.message])],[30,17,100]);
 return [summary,income,costs,detailCosts,products,assets,dep,pettySheet,notes];
}
function workbook(sheets){
 const styles=`<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><numFmts count="3"><numFmt numFmtId="164" formatCode="#,##0;[Red](#,##0);&quot;–&quot;"/><numFmt numFmtId="165" formatCode="0.0%"/><numFmt numFmtId="166" formatCode="dd mmm yyyy"/></numFmts><fonts count="3"><font><sz val="11"/><name val="Calibri"/><color rgb="FF172B4D"/></font><font><b/><sz val="16"/><name val="Calibri"/><color rgb="FFFFFFFF"/></font><font><b/><sz val="11"/><name val="Calibri"/><color rgb="FF172B4D"/></font></fonts><fills count="4"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF163B60"/><bgColor indexed="64"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFE8F0F7"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="2"><border/><border><bottom style="thin"><color rgb="FFCBD5E1"/></bottom></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="7"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" applyAlignment="1"><alignment horizontal="left" vertical="center" wrapText="1" indent="1"/></xf><xf numFmtId="0" fontId="1" fillId="2" borderId="0" applyAlignment="1"><alignment horizontal="left" vertical="center" wrapText="1" indent="1"/></xf><xf numFmtId="0" fontId="2" fillId="3" borderId="1" applyAlignment="1"><alignment horizontal="left" vertical="center" wrapText="1" indent="1"/></xf><xf numFmtId="164" fontId="0" fillId="0" borderId="0" applyAlignment="1"><alignment horizontal="right" vertical="center" indent="1"/></xf><xf numFmtId="165" fontId="2" fillId="0" borderId="0" applyAlignment="1"><alignment horizontal="right" vertical="center" indent="1"/></xf><xf numFmtId="166" fontId="0" fillId="0" borderId="0" applyAlignment="1"><alignment horizontal="left" vertical="center" indent="1"/></xf><xf numFmtId="164" fontId="2" fillId="3" borderId="1" applyAlignment="1"><alignment horizontal="right" vertical="center" indent="1"/></xf></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>`;
 const files={'xl/styles.xml':styles,'_rels/.rels':'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'};
 files['[Content_Types].xml']='<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>'+sheets.map((s,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join('')+'</Types>';
 files['xl/workbook.xml']='<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>'+sheets.map((s,i)=>`<sheet name="${xml(s.name)}" sheetId="${i+1}" r:id="rId${i+1}"/>`).join('')+'</sheets><definedNames>'+sheets.map((s,i)=>`<definedName name="_xlnm.Print_Titles" localSheetId="${i}">'${xml(s.name)}'!$${s.header}:$${s.header}</definedName><definedName name="_xlnm.Print_Area" localSheetId="${i}">'${xml(s.name)}'!$A$1:$${column(s.widths.length-1)}$${s.rows.length}</definedName>`).join('')+'</definedNames><calcPr calcId="191029" fullCalcOnLoad="1"/></workbook>';
 files['xl/_rels/workbook.xml.rels']='<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'+sheets.map((s,i)=>`<Relationship Id="rId${i+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join('')+`<Relationship Id="rId${sheets.length+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`;
 sheets.forEach((s,index)=>{const last=column(s.widths.length-1);files[`xl/worksheets/sheet${index+1}.xml`]='<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetPr><pageSetUpPr fitToPage="1"/></sheetPr><sheetViews><sheetView showGridLines="0" workbookViewId="0"><pane ySplit="'+s.header+'" topLeftCell="A'+(s.header+1)+'" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols>'+s.widths.map((w,i)=>`<col min="${i+1}" max="${i+1}" width="${w}" customWidth="1"/>`).join('')+'</cols><sheetData>'+s.rows.map((row,i)=>{const number=i+1,merged=s.merges?.includes(number),isTotal=s.totals?.includes(number);const height=number===1?32:merged?Math.max(23,Math.ceil(String(row[0]??'').length/s.widths.reduce((a,b)=>a+b,0))*15+6):Math.max(22,...row.map((v,j)=>Math.ceil(String(v?.value??v??'').length/(s.widths[j]||25))*15+6));return `<row r="${number}" ht="${height}" customHeight="1">`+row.map((v,j)=>{const o=v&&typeof v==='object'?v:{value:v},value=o.value??'',style=number===1?1:number===s.header||isTotal?o.style===4?4:typeof value==='number'?6:2:o.style??0,ref=column(j)+number;return typeof value==='number'?`<c r="${ref}" s="${style}">${o.formula?'<f>'+xml(o.formula)+'</f>':''}<v>${value}</v></c>`:`<c r="${ref}" s="${style}" t="inlineStr"><is><t xml:space="preserve">${xml(value)}</t></is></c>`;}).join('')+'</row>';}).join('')+'</sheetData>'+(s.filter&&s.rows.length>s.header?`<autoFilter ref="A${s.header}:${last}${s.rows.length}"/>`:'')+(s.merges?'<mergeCells count="'+s.merges.length+'">'+s.merges.map(n=>`<mergeCell ref="A${n}:${last}${n}"/>`).join('')+'</mergeCells>':'')+'<pageMargins left="0.3" right="0.3" top="0.45" bottom="0.45" header="0.2" footer="0.2"/><pageSetup paperSize="9" orientation="'+(index===0?'portrait':'landscape')+'" fitToWidth="1" fitToHeight="0"/><headerFooter><oddFooter>&amp;LBUMM Marala&amp;RHalaman &amp;P dari &amp;N</oddFooter></headerFooter></worksheet>';});return zip(files);
}
module.exports={sheets,workbook};
