// One calculation path for the dashboard, management report and export.
const {date,money,fail,today}=require('./domain.cjs');
const sum=(rows,key)=>rows.reduce((n,r)=>n+Number(r[key]||0),0);
const clean=v=>String(v??'').trim().slice(0,300);
const CATEGORIES=['Gaji dan Upah','Es dan Gas','Kebersihan','Listrik dan Air','Transportasi','Perlengkapan','Perbaikan','Komisi','Vendor','Operasional Lainnya'];
function validateCashChange(s,kind,d,id){
 const config=s.setting('finance')||{},existing=cashRows(s).filter(r=>r.id!==id),candidate=d&&(kind==='funds'||(d.source==='Petty Cash'&&(kind==='procurementcash'||d.status==='Dibayar')))?{...d,delta:kind==='funds'?d.amount:-d.amount,_sequence:Number.MAX_SAFE_INTEGER}:null;
 if(!candidate&&!cashRows(s).some(r=>r.id===id))return;
 const rows=[...existing,...(candidate?[candidate]:[])].sort((a,b)=>a.date.localeCompare(b.date)||a._sequence-b._sequence);
 if(config.pettyStart&&rows.some(r=>r.date<config.pettyStart))fail('Tanggal transaksi sebelum tanggal saldo awal Petty Cash.');
 let balance=config.pettyOpening??1000000;const days=new Map();for(const r of rows)days.set(r.date,(days.get(r.date)||0)+r.delta);for(const [day,delta] of days){balance+=delta;if(balance<0)fail('Saldo Petty Cash tidak cukup pada '+day+'. Periksa saldo awal dan dana masuk.');}
}
function period(f={}){if(f.from)date(f.from);if(f.to)date(f.to);if(f.from&&f.to&&f.from>f.to)fail('Rentang tanggal tidak valid.');return f;}
function matches(r,f){return (!f.from||r.date>=f.from)&&(!f.to||r.date<=f.to)&&(!f.unitId||r.unitId===f.unitId)&&(!f.q||JSON.stringify(r).toLowerCase().includes(f.q.toLowerCase()));}
function cashRows(s){return [...s.list('funds').map(r=>({...r,kind:'funds',recordId:r.id,delta:r.amount})),...s.list('expenses').filter(r=>r.source==='Petty Cash'&&r.status==='Dibayar').map(r=>({...r,kind:'expenses',recordId:r.id,delta:-r.amount})),...s.list('procurementcash').filter(r=>r.source==='Petty Cash').map(r=>({...r,kind:'procurements',recordId:r.procurementId,delta:-r.amount}))].sort((a,b)=>a.date.localeCompare(b.date)||a._sequence-b._sequence);}
function petty(s,p){if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(p))fail('Periode tidak valid.');const config=s.setting('finance')||{},all=cashRows(s),start=config.pettyStart||(all[0]?.date.slice(0,7)||p)+'-01',initial=config.pettyOpening??1000000;const before=p+'-01';const opening=(start<=before?initial:0)+sum(all.filter(r=>r.date>=start&&r.date<before),'delta');let running=opening;const history=all.filter(r=>r.date>=start&&r.date.startsWith(p)).map(r=>({...r,balance:running+=r.delta}));return {period:p,opening,incoming:sum(history.filter(r=>r.delta>0),'delta'),outgoing:Math.abs(sum(history.filter(r=>r.delta<0),'delta')),balance:running,history,confirmed:config.pettyOpening!==undefined,start,initial};}
function saveSettings(s,d,actor){const current=s.setting('finance')||{};if(d.pettyOpening!==undefined){if(d.pettyOpening==='')fail('Isi nominal saldo awal, termasuk 0 bila kosong.');current.pettyOpening=money(d.pettyOpening);current.pettyStart=date(d.pettyStart);if(!current.pettyStart.endsWith('-01'))fail('Gunakan tanggal pertama bulan untuk saldo awal.');const all=cashRows(s);if(all[0]&&current.pettyStart>all[0].date)fail('Tanggal saldo awal harus pada atau sebelum transaksi Petty Cash pertama.');}if(d.unitGroups){const groups={};for(const [id,label] of Object.entries(d.unitGroups)){s.ref(id,'units');groups[id]=clean(label);}current.unitGroups=groups;}s.setSetting('finance',current);s.audit(actor,'settings','finance');return current;}
function saveAsset(s,id,d,actor){const a=s.ref(id,'procurements');if(a.type!=='Aset/Peralatan'||a.status!=='Dibayar')fail('Pilih aset yang sudah dibayar.');const life=Number(d.life),residual=money(d.residual||0);if(!Number.isInteger(life)||life<1||life>600)fail('Masa manfaat harus 1–600 bulan.');if(residual>a.amount)fail('Nilai sisa melebihi nilai aset.');if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(d.start||'')||d.start<a.date.slice(0,7))fail('Bulan mulai penyusutan tidak boleh sebelum pembelian.');const plans=s.setting('assetPlans')||{};plans[id]={life,residual,start:d.start};s.setSetting('assetPlans',plans);s.audit(actor,'settings','assetPlan:'+id);return plans[id];}
function validateDetails(s,kind,d,id){
 if(!['sales','expenses'].includes(kind))return;
 const fields=kind==='sales'?['quantity','salePrice','unitCost']:['quantity','unitPrice'];
 const supplied=fields.some(k=>d[k]!==''&&d[k]!==undefined&&d[k]!==null);
 if(supplied){if(fields.some(k=>d[k]===''||d[k]===undefined||d[k]===null))fail('Lengkapi jumlah dan seluruh harga satuan, atau kosongkan semuanya untuk input total.');d.quantity=Number(d.quantity);if(!Number.isFinite(d.quantity)||d.quantity<=0||d.quantity>1e9||Math.abs(d.quantity*1000-Math.round(d.quantity*1000))>1e-6)fail('Jumlah harus positif, maksimal 3 desimal.');for(const k of fields.slice(1))d[k]=money(d[k]);d.amount=money(Math.round(d.quantity*d[fields[1]]));if(kind==='sales')d.cost=money(Math.round(d.quantity*d.unitCost));}else for(const k of fields)delete d[k];
 d.unit=clean(d.unit);d.recipient=clean(d.recipient);d.payPeriod=clean(d.payPeriod);if(d.payPeriod&&!/^\d{4}-(0[1-9]|1[0-2])$/.test(d.payPeriod))fail('Periode gaji gunakan YYYY-MM.');
 if(kind==='expenses'){
  if(d.costClass&&!['Operasional','HPP','Tercakup HPP invoice'].includes(d.costClass))fail('Kelompok biaya tidak valid.');
  if(d.invoiceId){const i=s.ref(d.invoiceId,'invoices');if(i.unitId!==d.unitId)fail('Unit biaya harus sama dengan invoice terkait.');}
  if(d.costClass==='Tercakup HPP invoice'){const i=s.ref(d.invoiceId,'invoices'),available=(i.items||[]).reduce((n,r)=>n+Math.round((r.cost||0)*r.qty),0);if(!available)fail('Invoice belum memiliki HPP. Pilih HPP tambahan atau lengkapi invoice dahulu.');const other=sum(s.list('expenses').filter(e=>e.id!==id&&e.invoiceId===d.invoiceId&&e.status==='Dibayar'&&e.costClass==='Tercakup HPP invoice'),'amount');if(d.status==='Dibayar'&&other+Number(d.amount)>available)fail('Total biaya yang ditandai tercakup melebihi HPP invoice. Pisahkan biaya tambahan sebagai HPP.');}
 }
}
function report(s,f={}){
 period(f);const units=s.list('units'),names=new Map(units.map(u=>[u.id,u.name])),config=s.setting('finance')||{},warnings=[],entries=[],live=require('./live-cost.cjs').calculator(s),allInvoices=s.list('invoices').map(live.invoice),invoices=new Map(allInvoices.map(i=>[i.id,i]));
 const warn=(r,message)=>warnings.push({date:r.date||'',number:r.number||r.id||'',message});
 const payments=s.list('payments').sort((a,b)=>a.date.localeCompare(b.date)||a._sequence-b._sequence),paid=new Map();
 for(const p of payments){const i=invoices.get(p.invoiceId);if(!i){if(matches(p,f))warn(p,'Pembayaran tidak memiliki invoice aktif.');continue;}const totalCost=(i.items||[]).reduce((n,j)=>n+Math.round((j.cost||0)*j.qty),0),before=paid.get(i.id)||0;paid.set(i.id,before+p.amount);const cost=i.total?Math.round(totalCost*(before+p.amount)/i.total)-Math.round(totalCost*before/i.total):0;const r={...p,number:i.number,description:i.customer?.name||p.customerName||'Pembayaran invoice',unitId:i.unitId,unitName:names.get(i.unitId)||'Unit tidak tersedia',amount:p.amount,cost,source:'Pembayaran invoice',invoiceDate:i.date};if(matches(r,f)){entries.push(r);if(!totalCost||(i.items||[]).some(j=>!j.cost))warn(r,'Sebagian/seluruh HPP invoice nol atau belum tersedia; periksa sebelum menyerahkan laporan.');}}
 for(const sale of s.list('sales').map(live.sale)){const r={...sale,cost:sale.cost||0,unitName:names.get(sale.unitId)||'Unit tidak tersedia',source:sale.posDayId?'Rekap kasir disetujui':'Penjualan langsung'};if(matches(r,f)){entries.push(r);if(!r.cost)warn(r,'HPP penjualan nol/belum tersedia; periksa apakah memang tanpa biaya.');if(!r.posDayId&&(!r.productId||!Number(r.quantity)))warn(r,'HPP memakai total input transaksi karena produk atau jumlah belum terhubung ke master.');}}
 entries.sort((a,b)=>a.date.localeCompare(b.date)||String(a.number).localeCompare(String(b.number)));
 const expenses=s.list('expenses',f).filter(e=>e.status==='Dibayar').map(e=>({...e,costClass:e.costClass||'Operasional',unitName:names.get(e.unitId)||'Unit tidak tersedia',invoiceNumber:invoices.get(e.invoiceId)?.number||'',classificationMissing:!e.costClass}));
 for(const e of expenses){if(e.classificationMissing)warn(e,'Kelompok biaya belum dikonfirmasi; sementara dimasukkan ke Operasional.');if(!CATEGORIES.includes(e.category))warn(e,'Kategori lama/custom: '+e.category+'. Tinjau pengelompokannya.');}
 const direct=expenses.filter(e=>e.costClass==='HPP'),operating=expenses.filter(e=>e.costClass==='Operasional'),excluded=expenses.filter(e=>e.costClass==='Tercakup HPP invoice');
 for(const e of direct)if(e.invoiceId&&(invoices.get(e.invoiceId)?.items||[]).some(j=>j.cost))warn(e,'Biaya HPP tambahan terkait invoice yang sudah memiliki HPP. Pastikan biaya ini belum tercakup di HPP invoice.');
 for(const e of excluded)warn(e,'Tidak dikurangi lagi: ditandai tercakup HPP invoice '+e.invoiceNumber+'. Cocokkan dengan rincian HPP invoice.');
 const plans=s.setting('assetPlans')||{},assets=[],depreciationRows=[];
 const end=f.to||today(),start=f.from||'0001-01-01';
 for(const a of s.list('procurements').filter(a=>a.type==='Aset/Peralatan'&&a.status==='Dibayar'&&a.date<=end&&(!f.unitId||a.unitId===f.unitId))){const plan=plans[a.id];let expense=0,accumulated=0;if(plan){const [y,m]=plan.start.split('-').map(Number),base=a.amount-plan.residual;for(let index=0;index<plan.life;index++){const dt=new Date(Date.UTC(y,m+index,0)).toISOString().slice(0,10);if(dt>end)break;const value=Math.round(base*(index+1)/plan.life)-Math.round(base*index/plan.life);accumulated+=value;if(dt>=start){const r={date:dt,number:a.number,description:a.name,unitId:a.unitId,unitName:names.get(a.unitId),amount:value,category:'Penyusutan Aset',costClass:'Operasional'};if(matches(r,f)){expense+=value;depreciationRows.push(r);}}}}else warn(a,'Aset belum memiliki masa manfaat/penyusutan. Laba belum mencakup penyusutan aset ini.');assets.push({...a,plan,expense,accumulated,bookValue:a.amount-accumulated,unitName:names.get(a.unitId)||''});}
 const unitRows=units.map(u=>{const e=entries.filter(r=>r.unitId===u.id),x=direct.filter(r=>r.unitId===u.id),revenue=sum(e,'amount'),cost=sum(e,'cost')+sum(x,'amount');return {id:u.id,name:u.name,group:config.unitGroups?.[u.id]||u.name,revenue,cost,grossProfit:revenue-cost};});
 const categories=Object.values(operating.reduce((out,e)=>{out[e.category]??={name:e.category,amount:0};out[e.category].amount+=e.amount;return out;},Object.create(null)));
 const depreciation=sum(depreciationRows,'amount');if(depreciation)categories.push({name:'Penyusutan Aset (non-tunai)',amount:depreciation});
 const revenue=sum(entries,'amount'),cost=sum(entries,'cost')+sum(direct,'amount'),outgoing=sum(operating,'amount')+depreciation,grossProfit=revenue-cost,profit=grossProfit-outgoing;
 const pending=s.list('postickets').filter(t=>t.status==='Selesai'&&matches({...t,unitId:require('./pos.cjs').unit(s)?.id},f)&&!s.list('sales').some(x=>x.posDayId&&x.date===t.date&&(s.get(x.posDayId,'posdays').batch||0)===(t.batch||0)));if(pending.length)warn({number:'Kasir Teko'},pending.length+' transaksi kasir belum masuk rekap omzet disetujui.');
 if(petty(s,(f.to||today()).slice(0,7)).balance<0)warn({number:'Petty Cash'},'Saldo kas negatif. Periksa saldo awal dan kelengkapan dana masuk sebelum mencatat pengeluaran baru.');
 if(config.pettyOpening===undefined)warn({number:'Petty Cash'},'Saldo awal belum dikonfirmasi. Buku kas menggunakan saldo awal lama Rp1.000.000 satu kali, lalu saldo diteruskan.');
 const monthlyMap=new Map();for(const e of entries){const key=e.date.slice(0,7);monthlyMap.set(key,(monthlyMap.get(key)||0)+e.amount);}const keys=[...monthlyMap.keys()].sort(),first=f.from?.slice(0,7)||keys[0]||today().slice(0,7),last=f.to?.slice(0,7)||keys.at(-1)||first,monthly=[];let [y,m]=first.split('-').map(Number);while(`${y}-${String(m).padStart(2,'0')}`<=last&&monthly.length<1200){const month=`${y}-${String(m).padStart(2,'0')}`;monthly.push({month,revenue:monthlyMap.get(month)||0});if(++m===13){m=1;y++;}}
 const tekoId=require('./pos.cjs').unit(s)?.id,tekoCost=unitRows.find(u=>u.id===tekoId)?.cost||0;
 const products=Object.values(entries.filter(r=>r.source==='Penjualan langsung').reduce((o,r)=>{const key=r.productId||r.description;o[key]??={name:r.productName||r.description,qty:0,amount:0,cost:0};o[key].qty+=Number(r.quantity||0);o[key].amount+=r.amount;o[key].cost+=r.cost;return o;},Object.create(null)));
 return {from:f.from||'',to:f.to||'',unitId:f.unitId||'',query:f.q||'',revenue,cost,outgoing,profit,grossProfit,grossMargin:revenue?grossProfit/revenue:null,netMargin:revenue?profit/revenue:null,tekoCost,otherCost:cost-tekoCost,depreciation,units:unitRows,categories,entries,expenses,direct,excluded,assets,depreciationRows,warnings,monthly,products,count:entries.length,invoices:allInvoices,sales:s.list('sales',f),pendingCount:pending.length};
}
module.exports={report,petty,saveSettings,saveAsset,validateDetails,validateCashChange,CATEGORIES,cashRows};
