const LOCATIONS=['Gudang','Teko Marala'];
function normalize(store){
 const stocks=store.list('stocks');
 for(const old of stocks){if(old.stockItemId)continue;
  const key=old.productId||`${old.name.toLowerCase()}|${old.unit.toLowerCase()}`;
  let item=store.list('stockitems').find(i=>i.migrationKey===key);
  if(!item)item=store.put('stockitems',{name:old.name,unit:old.unit,price:old.price,minWarehouse:0,maxWarehouse:1000000,minTeko:0,maxTeko:1000000,migrationKey:key});
  const suffix=old.location==='Gudang'?'Warehouse':'Teko';item['min'+suffix]=old.min;item['max'+suffix]=old.max;store.put('stockitems',item,item.id);
  const d={...old,stockItemId:item.id,legacyProductId:old.productId,legacyUnitId:old.unitId};delete d.productId;delete d.unitId;delete d._sequence;store.put('stocks',d,old.id);
 }
 for(const item of store.list('stockitems'))for(const location of LOCATIONS){if(!store.list('stocks').some(s=>s.stockItemId===item.id&&s.location===location)){const suffix=location==='Gudang'?'Warehouse':'Teko';store.put('stocks',{stockItemId:item.id,name:item.name,unit:item.unit,location,min:item['min'+suffix],max:item['max'+suffix],price:item.price});}}
 for(const kind of ['movements','opnames'])for(const row of store.list(kind)){if(!row.unitId&&!row.productId)continue;const d={...row,legacyUnitId:row.unitId,legacyProductId:row.productId};delete d.unitId;delete d.productId;delete d._sequence;store.put(kind,d,row.id);}
}
function saveItem(store,input,id,actor){const {money,fail}=require('./domain.cjs');const old=id?store.get(id,'stockitems'):null;const name=String(input.name||'').trim(),unit=String(input.unit||'').trim();if(!name||!unit)fail('Nama barang dan satuan wajib diisi.');if(store.list('stockitems').some(i=>i.id!==id&&i.name.toLowerCase()===name.toLowerCase()))fail('Nama barang stok sudah terdaftar.');const d={name,unit,category:String(input.category??old?.category??'').trim().slice(0,100),price:money(input.price),migrationKey:old?.migrationKey};for(const k of ['minWarehouse','maxWarehouse','minTeko','maxTeko']){const n=Number(input[k]);if(!Number.isFinite(n)||n<0||n>1e9||Math.abs(n*1000-Math.round(n*1000))>1e-6)fail('Batas stok harus angka positif, maksimal tiga desimal.');d[k]=n;}if(d.maxWarehouse<d.minWarehouse||d.maxTeko<d.minTeko)fail('Maksimum stok harus >= minimum pada setiap lokasi.');if(old&&unit!==old.unit&&store.list('stocks').filter(s=>s.stockItemId===id).some(s=>store.stockQuantity(s.id)!==0))fail('Satuan barang dengan saldo stok tidak dapat diubah.');const item=store.put('stockitems',d,id);for(const location of LOCATIONS){const existing=store.list('stocks').find(s=>s.stockItemId===item.id&&s.location===location),suffix=location==='Gudang'?'Warehouse':'Teko';const locationRow=store.put('stocks',{stockItemId:item.id,name,unit,category:d.category,price:d.price,location,min:d['min'+suffix],max:d['max'+suffix]},existing?.id);store.audit(actor,existing?'edit':'create','stocks:'+locationRow.id);}store.audit(actor,old?'edit':'create','stockitems:'+item.id);return item;}
function transfer(store,d,actor){const {date,fail}=require('./domain.cjs');const item=store.get(d.stockItemId,'stockitems');date(d.date);if(!LOCATIONS.includes(d.from)||!LOCATIONS.includes(d.to)||d.from===d.to)fail('Pilih lokasi asal dan tujuan yang berbeda.');const quantity=Number(d.quantity);if(!Number.isFinite(quantity)||quantity<=0)fail('Jumlah transfer harus lebih dari nol.');const stock=location=>store.list('stocks').find(s=>s.stockItemId===item.id&&s.location===location);const source=stock(d.from),target=stock(d.to);if(!source||!target)fail('Lokasi barang tidak ditemukan.');return store.tx(()=>{const value=store.stockView(source,d.date),transferValue=Math.round(quantity*value.price);const t=store.put('transfers',{number:store.nextNumber('transfers','TRF',d.date),date:d.date,stockItemId:item.id,name:item.name,unit:item.unit,from:d.from,to:d.to,quantity,price:value.price,value:transferValue,notes:String(d.notes||'').trim()});for(const [s,direction]of [[source,'Keluar'],[target,'Masuk']]){const movement=store.save('movements',{stockId:s.id,date:d.date,direction,quantity,price:item.price,transferId:t.id,notes:`Transfer ${t.number}: ${d.from} → ${d.to}${d.notes?' · '+d.notes:''}`},null,actor);if(store.list('movements').some(m=>m.stockId===source.id&&m.acquisitionValue!==undefined))store.put('movements',{...movement,price:value.price,acquisitionValue:direction==='Masuk'?transferValue:undefined},movement.id);}store.audit(actor,'transfer',t.id);return t;});}
function categorize(store,kind,rows,f={}){
 const masters=new Map(store.list('stockitems').map(r=>[r.id,r]));
 const stocks=new Map(['movements','opnames'].includes(kind)?store.list('stocks').map(r=>[r.id,r]):[]);
 return rows.map(r=>{const m=masters.get(kind==='stockitems'?r.id:r.stockItemId||stocks.get(r.stockId)?.stockItemId);return {...r,category:(m?m.category:r.category)||''};}).filter(r=>(!f.category||r.category===f.category||(f.category==='__none__'&&!r.category))&&(!f.location||r.location===f.location||r.from===f.location||r.to===f.location));
}
module.exports={normalize,saveItem,transfer,categorize};
