const crypto=require('node:crypto');
const {fail}=require('./domain.cjs');
function migrate(store,legacy,actor){
 if(!legacy||typeof legacy!=='object')fail('Data lama tidak valid.');
 const raw=JSON.stringify(legacy),digest=crypto.createHash('sha256').update(raw).digest('hex');
 if(store.db.prepare('SELECT digest FROM imports WHERE digest=?').get(digest))return {message:'Data ini sudah diimpor sebelumnya.',count:0};
 const asMoney=v=>typeof v==='number'?v:Number(String(v||'0').replace(/[^0-9]/g,''));
 const asDate=v=>{if(/^\d{4}-\d{2}-\d{2}$/.test(v||''))return v;const m=String(v).match(/(\d{1,2})\s+(\w+)\s+(\d{4})/);const months=['Jan','Feb','Mar','Apr','Mei','Jun','Jul','Agu','Sep','Okt','Nov','Des'];if(!m||!months.includes(m[2]))fail('Tanggal data lama tidak dikenal: '+v);return `${m[3]}-${String(months.indexOf(m[2])+1).padStart(2,'0')}-${m[1].padStart(2,'0')}`;};
 let count=0;const add=(kind,d)=>{count++;const record=store.put(kind,d);store.audit(actor,'import',kind+':'+record.id);return record;};
 const unit=name=>store.list('units').find(u=>u.name===name)||add('units',{name:name||'Data Lama',notes:'Migrasi'});
 const customer=name=>store.list('customers').find(c=>c.name===name)||add('customers',{name,phone:'',notes:'Migrasi'});
 for(const u of legacy.units||[])unit(u);
 for(const c of legacy.customers||[]){if(!Array.isArray(c))fail('Format customer lama tidak valid.');if(!store.list('customers').some(x=>x.name===c[0]))add('customers',{name:c[0],phone:c[1],notes:c[2]||''});}
 for(const p of legacy.products||[]){if(!store.list('products').some(x=>x.code===p[0]))add('products',{code:p[0],name:p[1],unitId:unit(p[2]).id,type:p[3],unit:p[4],cost:asMoney(p[5]),price:asMoney(p[6])});}
 for(const inv of legacy.invoices||[]){if(store.list('invoices').some(x=>x.number===inv[0]))continue;const detail=legacy.invoiceDetails?.[inv[0]],total=asMoney(inv[3]);if(!Number.isSafeInteger(total))fail('Nominal invoice lama tidak valid.');add('invoices',{number:inv[0],customerId:customer(inv[1]).id,customer:{name:inv[1],phone:customer(inv[1]).phone},unitId:unit('Data Lama').id,date:asDate(inv[2]),dueDate:asDate(inv[2]),total,subtotal:detail?.subtotal??total,discount:detail?.discount||0,itemDiscount:0,other:detail?.other||0,items:(detail?.items||[]).map(i=>({...i,discount:0,unit:i.unit||'Item',subtotal:Math.round(i.price*i.qty)})),eventDate:legacy.invoiceEventDates?.[inv[0]]&&legacy.invoiceEventDates[inv[0]]!=='—'?asDate(legacy.invoiceEventDates[inv[0]]):'',legacy:true,identity:store.setting('identity'),options:store.setting('invoice'),bank:null,notes:'Data lama: rincian yang sebelumnya tidak tersimpan tidak direkonstruksi.'});}
 for(const p of legacy.payments||[]){const inv=store.list('invoices').find(i=>i.number===p.invoice);if(!inv)fail('Invoice pembayaran lama tidak ditemukan.');const d={date:asDate(p.date),invoiceId:inv.id,customerName:p.customer,method:p.method,amount:asMoney(p.amount),legacy:true};if(!store.list('payments').some(x=>x.invoiceId===d.invoiceId&&x.date===d.date&&x.amount===d.amount&&x.method===d.method))add('payments',d);}
 for(const r of legacy.revenues||[]){const number='LAMA-OMZET-'+crypto.createHash('sha256').update(JSON.stringify(r)).digest('hex').slice(0,12);if(!store.list('sales').some(x=>x.number===number))add('sales',{number,date:asDate(r[0]),unitId:unit(r[1]).id,amount:asMoney(r[2]),method:r[3],description:r[4],cost:0,legacy:true});}
for(const r of legacy.stock||[]){const u=unit('Data Lama');let p=store.list('products').find(x=>x.name===r[0]);if(!p)p=add('products',{code:'LAMA-'+crypto.randomBytes(4).toString('hex'),name:r[0],unitId:u.id,type:'Produk',unit:r[3],cost:0,price:0});if(store.list('stocks').some(s=>(s.productId===p.id||s.legacyProductId===p.id)&&s.location===r[1]))continue;const quantity=Number(r[2]),price=quantity?Math.round(asMoney(r[4])/quantity):0;const s=add('stocks',{name:r[0],productId:p.id,unitId:p.unitId,location:r[1],unit:r[3],min:0,max:1000000,price});add('movements',{stockId:s.id,productId:p.id,unitId:p.unitId,name:s.name,location:s.location,unit:s.unit,date:'2026-09-22',direction:'Masuk',quantity,delta:quantity,price,notes:'Saldo awal dari prototipe'});}
 for(const r of legacy.expenses||[]){const number='LAMA-BIAYA-'+crypto.createHash('sha256').update(JSON.stringify(r)).digest('hex').slice(0,12);if(!store.list('expenses').some(x=>x.number===number))add('expenses',{number,date:asDate(r[0]),unitId:unit('Data Lama').id,category:r[2],description:r[3],amount:asMoney(r[4]),source:r[1]==='Petty Cash'?'Petty Cash':'Lainnya',method:'Cash',status:r[1]==='Pengajuan'?'Draft':'Dibayar',notes:'Migrasi prototipe',proof:''});}
 require('./inventory.cjs').normalize(store);store.db.prepare('INSERT INTO imports VALUES(?,?,?)').run(digest,raw,new Date().toISOString());store.audit(actor,'migration',digest);return {message:'Migrasi selesai. Salinan data asli disimpan.',count};
}
module.exports={migrate};
