const crypto=require('node:crypto');
const {money,date,fail,today}=require('./domain.cjs');
const clean=v=>String(v??'').trim().slice(0,500);
function unit(store){const saved=store.setting('posUnit');return store.list('units').find(u=>u.id===saved?.id)||store.list('units').find(u=>u.name.toLowerCase()==='teko marala');}
function day(store,dt,batch=0){date(dt);return store.list('posdays',{from:dt,to:dt}).find(d=>(d.batch||0)===batch);}
function paymentBatch(store,dt){if(store.setting('posImmediatePayments')?.enabled){const batches=[...store.list('posdays',{from:dt,to:dt}),...store.list('postickets',{from:dt,to:dt})].map(t=>t.batch||0);return batches.length?Math.max(...batches)+1:0;}const ds=store.list('posdays',{from:dt,to:dt});let batch=Math.max(0,...ds.map(d=>d.batch||0));if(day(store,dt,batch)?.status&&day(store,dt,batch).status!=='Open')batch++;return batch;}
function target(d){const [dt,b]=String(d.date).split('~');const batch=Number(b||0);if(!Number.isSafeInteger(batch)||batch<0)fail('Rekap tidak valid.');return {dt:date(dt),batch};}
function ensureOpen(store,dt,batch=0){if(day(store,dt,batch)?.status&&day(store,dt,batch).status!=='Open')fail('Tanggal ini sudah diajukan/disetujui. Super Admin harus membuka revisi terlebih dahulu.',409);}
function saveProduct(store,d,id,actor){return store.tx(()=>{
 const name=clean(d.name),category=clean(d.category);if(!name||!category)fail('Nama dan kategori wajib diisi.');
 if(store.list('posproducts').some(p=>p.id!==id&&p.name.toLowerCase()===name.toLowerCase()))fail('Nama produk sudah ada.');
 if(id)store.get(id,'posproducts');const p=store.put('posproducts',{name,category,price:money(d.price),cost:money(d.cost),active:d.active!==false,stockRecipe:require('./pos-stock.cjs').recipe(store,d.stockRecipe??(id?store.get(id,'posproducts').stockRecipe:[])??[])},id);store.audit(actor,id?'pos-product-edit':'pos-product-create',p.id);return p;
});}
function createSale(store,d,actor){return store.tx(()=>{
 if(!/^[a-zA-Z0-9-]{16,80}$/.test(d.key||''))fail('Kode transaksi tidak valid.');
 const number='POS-'+d.key,existing=store.db.prepare("SELECT id,deleted FROM records WHERE kind IN ('postickets','posorders') AND number=?").get(number);if(existing){if(existing.deleted)fail('Pesanan sudah dihapus. Muat ulang kasir.',409);return store.get(existing.id);}
 const dt=date(d.date);if(dt!==today())fail('Tanggal transaksi kasir harus hari ini (WIB). Muat ulang kasir.',409);
 const queued=d.mode==='queue',debt=!queued&&d.method==='Hutang',immediate=store.setting('posImmediatePayments')?.enabled===true,batch=immediate&&!queued&&!debt?paymentBatch(store,dt):0;if(!queued&&!debt)ensureOpen(store,dt,batch);
 if(!queued&&!['Cash','QRIS','Hutang'].includes(d.method))fail('Pilih Cash, QRIS, atau Hutang.');if(!queued&&d.method==='QRIS'&&d.qrisConfirmed!==true)fail('Konfirmasi pembayaran QRIS terlebih dahulu.');
 if(debt&&!clean(d.customerName))fail('Nama customer wajib untuk hutang.');
 if(!Array.isArray(d.items)||!d.items.length||d.items.length>100)fail('Pilih minimal satu produk, maksimal 100 item.');
 const items=d.items.map(x=>{const p=store.get(x.productId,'posproducts'),qty=Number(x.qty);if(!p.active)fail('Produk tidak aktif: '+p.name);if(!Number.isSafeInteger(qty)||qty<1||qty>10000)fail('Jumlah produk harus 1–10.000.');return {productId:p.id,name:p.name,category:p.category,stockRecipe:p.stockRecipe||[],qty,price:p.price,cost:p.cost,gross:money(p.price*qty)};});
 const subtotal=money(items.reduce((s,i)=>s+i.gross,0)),discount=money(d.discount||0);if(discount>subtotal)fail('Diskon melebihi subtotal.');if(discount&&!clean(d.discountReason))fail('Isi alasan diskon.');
 // Cumulative allocation preserves every rupiah, even for split discounts.
 let cumulative=0,allocated=0;for(const i of items){cumulative+=i.gross;const next=subtotal?Math.round(discount*cumulative/subtotal):0;i.discount=next-allocated;allocated=next;i.amount=i.gross-i.discount;i.hpp=money(i.cost*i.qty);}
 if(d.expectedAmount!==undefined&&Number(d.expectedAmount)!==subtotal-discount)fail('Harga berubah. Muat ulang kasir dan periksa total sebelum menyimpan.',409);const amount=subtotal-discount,cost=money(items.reduce((s,i)=>s+i.hpp,0)),cash=queued||debt?0:d.method==='Cash'?money(d.cash):amount;if(!queued&&!debt&&cash<amount)fail('Uang tunai kurang dari total.');
 const data={number,date:dt,at:new Date().toISOString(),items,subtotal,discount,discountReason:clean(d.discountReason),amount,cost,customerName:clean(d.customerName),phone:clean(d.phone),method:queued?'Belum dibayar':d.method,cash,change:queued||debt?0:cash-amount,status:queued?'Menunggu':debt?'Hutang':'Selesai',actor,notes:clean(d.notes)};
 if(queued||debt){if(!amount)fail('Total pesanan belum dibayar harus lebih dari nol.');data.orderType=queued?'queue':'debt';data.balance=amount;if(queued){const n=store.db.prepare("SELECT count(*) n FROM records WHERE kind='posorders' AND date=? AND json_extract(data,'$.queueNumber') IS NOT NULL").get(dt).n+1;data.queueNumber='A'+String(n).padStart(3,'0');}const order=store.put('posorders',data);store.audit(actor,'create','posorders:'+order.id);return order;}
 const t=store.put('postickets',{...data,batch,immediate});store.audit(actor,'pos-sale',t.id);if(immediate)settle(store,t,actor);return t;
});}
function voidSale(store,id,reason,actor){return store.tx(()=>{const t=store.get(id,'postickets');if(t.status==='Batal')fail('Transaksi sudah dibatalkan.');if(!clean(reason))fail('Alasan pembatalan wajib diisi.');if(t.immediate&&day(store,t.date,t.batch||0)?.status==='Approved')changeDay(store,{date:t.date+'~'+(t.batch||0),reason},'reopen',{id:actor},true);ensureOpen(store,t.date,t.batch||0);const v=store.put('postickets',{...t,status:'Batal',voidReason:clean(reason),voidAt:new Date().toISOString(),voidActor:actor},id);store.audit(actor,'pos-void',id);if(t.orderId){const o=store.get(t.orderId,'posorders');store.put('posorders',{...o,status:'Batal',balance:0,voidReason:clean(reason)},o.id);store.audit(actor,'pos-void','posorders:'+o.id);}return v;});}
function summary(store,dt,batch=0){const tickets=store.list('postickets',{from:dt,to:dt}).filter(t=>(t.batch||0)===batch),valid=tickets.filter(t=>t.status==='Selesai');return {tickets,valid,count:valid.length,amount:valid.reduce((s,t)=>s+t.amount,0),cost:valid.reduce((s,t)=>s+t.cost,0),cash:valid.filter(t=>t.method==='Cash').reduce((s,t)=>s+t.amount,0),qris:valid.filter(t=>t.method==='QRIS').reduce((s,t)=>s+t.amount,0)};}
function digest(s){return crypto.createHash('sha256').update(JSON.stringify(s.tickets)).digest('hex');}
function settle(store,t,actor){const d={date:t.date+'~'+(t.batch||0),countedCash:t.method==='Cash'?t.amount:0},user={id:actor};changeDay(store,d,'submit',user,true);changeDay(store,d,'approve',user,true);store.audit(actor,'pos-auto-post',t.id);}
function changeDay(store,d,action,user,automatic=false){return store.tx(()=>{
 if(store.setting('posImmediatePayments')?.enabled&&!automatic)fail('Pembayaran kasir masuk laporan otomatis. Rekap manual tidak diperlukan.',409);
 const {dt,batch}=target(d),old=day(store,dt,batch),s=summary(store,dt,batch);if(dt>today())fail('Tanggal belum berlangsung.');
 if(action==='submit'){
  if(old&&old.status!=='Open')fail('Rekap sudah diajukan/disetujui.',409);if(!s.count)fail('Belum ada transaksi selesai.');
  const countedCash=money(d.countedCash),difference=countedCash-s.cash;if(difference&&!clean(d.reason))fail('Isi alasan selisih kas.');
  const row=store.put('posdays',{date:dt,batch,status:'Submitted',amount:s.amount,cost:s.cost,cash:s.cash,qris:s.qris,countedCash,difference,reason:clean(d.reason),digest:digest(s),revision:(old?.revision||0)+1,submittedBy:user.id,submittedAt:new Date().toISOString()},old?.id);store.audit(user.id,'pos-submit',row.id);return row;
 }
 if(!automatic&&user.role!=='SUPER ADMIN')fail('Hanya Super Admin dapat menyetujui atau membuka revisi.',403);
 if(action==='approve'){
  if(old?.status!=='Submitted')fail('Rekap harus diajukan dan belum disetujui.',409);if(old.digest!==digest(s))fail('Rincian berubah. Ajukan ulang rekap.',409);
  require('./pos-stock.cjs').approve(store,old,s.valid,user.id);
  let u=unit(store);if(!u)u=store.save('units',{name:'Teko Marala'},undefined,user.id);store.setSetting('posUnit',{id:u.id});
  const sale=store.save('sales',{date:dt,unitId:u.id,number:'TEKO/'+dt+'/'+batch+'/'+old.revision,description:'Rekap kasir Teko Marala '+dt+(batch?' tambahan '+batch:''),amount:s.amount,cost:s.cost,method:'Cash + QRIS',posDayId:old.id},undefined,user.id);
  const row=store.put('posdays',{...old,status:'Approved',saleId:sale.id,approvedBy:user.id,approvedAt:new Date().toISOString()},old.id);store.audit(user.id,'pos-approve',row.id);return row;
 }
 if(action==='reopen'){
  if(!old||old.status==='Open')fail('Rekap belum diajukan.');if(!clean(d.reason))fail('Alasan revisi wajib diisi.');
  store.put('poshistory',{...old,id:undefined,reasonRevision:clean(d.reason),reopenedBy:user.id,reopenedAt:new Date().toISOString()});
  require('./pos-stock.cjs').reopen(store,old,user.id);
  if(old.saleId){store.db.prepare('UPDATE records SET deleted=1 WHERE id=?').run(old.saleId);store.audit(user.id,'delete','sales:'+old.saleId);}
  const row=store.put('posdays',{date:dt,batch,status:'Open',revision:old.revision,reopenReason:clean(d.reason)},old.id);store.audit(user.id,'pos-reopen',row.id);return row;
 }
 fail('Tindakan tidak valid.');
});}
function report(store,month,range={}){if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(month))fail('Pilih bulan laporan.');const last=new Date(Date.UTC(Number(month.slice(0,4)),Number(month.slice(5)),0)).getUTCDate(),defaultDates=Array.from({length:last},(_,i)=>month+'-'+String(i+1).padStart(2,'0'));const from=date(range.from||defaultDates[0]),to=date(range.to||defaultDates.at(-1));const span=Math.round((Date.parse(to)-Date.parse(from))/86400000);if(span<0||span>366)fail('Pilih rentang tanggal maksimal 367 hari.');const dates=Array.from({length:span+1},(_,i)=>new Date(Date.parse(from)+i*86400000).toISOString().slice(0,10));const tickets=store.list('postickets',{from:dates[0],to:dates.at(-1)}).map(require('./live-cost.cjs').calculator(store).ticket),days=store.list('posdays',{from:dates[0],to:dates.at(-1)}),history=store.list('poshistory',{from:dates[0],to:dates.at(-1)}),state=new Map(days.map(d=>[d.date+'~'+(d.batch||0),d]));
 const daily=dates.flatMap(dt=>[...new Set([0,...days.filter(d=>d.date===dt).map(d=>d.batch||0),...tickets.filter(t=>t.date===dt).map(t=>t.batch||0)])].sort((a,b)=>a-b).map(batch=>{const all=tickets.filter(t=>t.date===dt&&(t.batch||0)===batch),valid=all.filter(t=>t.status==='Selesai'),d=state.get(dt+'~'+batch);return {key:dt+'~'+batch,batch,trace:d?._trace,id:d?.id,date:dt,status:d?.status||'Open',count:valid.length,voidCount:all.length-valid.length,amount:valid.reduce((s,t)=>s+t.amount,0),cost:valid.reduce((s,t)=>s+t.cost,0),cash:valid.filter(t=>t.method==='Cash').reduce((s,t)=>s+t.amount,0),qris:valid.filter(t=>t.method==='QRIS').reduce((s,t)=>s+t.amount,0),countedCash:d?.countedCash??null,difference:d?.difference??null,reason:d?.reason||d?.reopenReason||'',revision:d?.revision||0};}));
 const detailMap=new Map();for(const t of tickets.filter(t=>t.status==='Selesai'))for(const i of t.items){const key=t.date+'|'+(t.batch||0)+'|'+i.productId;const r=detailMap.get(key)||{date:t.date,productId:i.productId,name:i.name,category:i.category,qty:0,amount:0,cost:0,status:state.get(t.date+'~'+(t.batch||0))?.status||'Open'};r.qty+=i.qty;r.amount+=i.amount;r.cost+=i.hpp;detailMap.set(key,r);}
 const details=[...detailMap.values()].sort((a,b)=>a.date.localeCompare(b.date)||a.name.localeCompare(b.name)),productMap=new Map();for(const r of details){const p=productMap.get(r.productId)||{productId:r.productId,name:r.name,category:r.category,qty:0,amount:0,cost:0,days:0,approvedAmount:0};p.qty+=r.qty;p.amount+=r.amount;p.cost+=r.cost;p.days=new Set(details.filter(x=>x.productId===r.productId).map(x=>x.date)).size;if(r.status==='Approved')p.approvedAmount+=r.amount;productMap.set(r.productId,p);}
 const approved=daily.filter(d=>d.status==='Approved'),pending=daily.filter(d=>d.count&&d.status!=='Approved');const ranked=store.list('posproducts').filter(p=>p.active).map(p=>productMap.get(p.id)||{productId:p.id,name:p.name,qty:0});const top=[...ranked].sort((a,b)=>b.qty-a.qty||a.name.localeCompare(b.name)).filter(p=>p.qty>0).slice(0,5),least=[...ranked].sort((a,b)=>a.qty-b.qty||a.name.localeCompare(b.name)).slice(0,5);return {month:from.slice(0,7)===to.slice(0,7)?from.slice(0,7):from+' s.d. '+to,from,to,top,least,dates,daily,details,products:[...productMap.values()].sort((a,b)=>b.qty-a.qty),tickets,history,orders:store.list('posorders',{from,to}),pendingDates:[...new Set(pending.map(d=>d.date))],final:pending.length===0,amount:daily.reduce((s,d)=>s+d.amount,0),approvedAmount:approved.reduce((s,d)=>s+d.amount,0),approvedCost:approved.reduce((s,d)=>s+d.cost,0),cost:daily.reduce((s,d)=>s+d.cost,0),count:daily.reduce((s,d)=>s+d.count,0)};
}
function sheets(r){const status=s=>({Open:'Belum diajukan',Submitted:'Menunggu approval',Approved:'Disetujui'})[s]||s;const dayLabel=dt=>new Date(dt+'T00:00:00Z').toLocaleDateString('id-ID',{weekday:'long',timeZone:'UTC'});
 const approved=r.details.filter(d=>d.status==='Approved'),pending=r.details.filter(d=>d.status!=='Approved');
 const detailRows=rows=>[['Hari','Tanggal','Produk','Kategori','Jumlah','Penjualan bersih','HPP standar','Laba kotor','Status'],...rows.map(d=>[dayLabel(d.date),d.date,d.name,d.category,d.qty,d.amount,d.cost,d.amount-d.cost,status(d.status)])];
 const matrix=onlyApproved=>[['Produk',...r.dates,'Total'],...r.products.map(p=>{const values=r.dates.map(date=>r.details.filter(d=>d.productId===p.productId&&d.date===date&&(!onlyApproved||d.status==='Approved')).reduce((s,d)=>s+d.qty,0));return [p.name,...values,values.reduce((s,n)=>s+n,0)];})];
 return [
 {name:'Ringkasan',rows:[['Laporan Teko Marala',r.month],['Status',r.final?'Final':'Belum Final'],['Tanggal belum disetujui',r.pendingDates.join(', ')],['Omzet disetujui',r.approvedAmount],['HPP standar disetujui',r.approvedCost],['Laba kotor disetujui',r.approvedAmount-r.approvedCost],['Omzet operasional (semua)',r.amount],['Jumlah transaksi selesai',r.count],['Catatan','HPP standar per produk; bukan pemakaian bahan aktual. Data penjualan manual lama tidak memiliki rincian kasir.']]},
 {name:'Produk Harian Disetujui',rows:detailRows(approved)}, {name:'Produk Harian Pending',rows:detailRows(pending)},
 {name:'Matriks Disetujui',rows:matrix(true)},{name:'Matriks Operasional',rows:matrix(false)},
 {name:'Rekap Harian',rows:[['Tanggal','Rekap','Status','Transaksi','Batal','Cash','QRIS','Omzet','HPP standar','Laba kotor','Kas dihitung','Selisih kas','Alasan','Revisi'],...r.daily.map(d=>[d.date,d.batch?'Tambahan '+d.batch:'Utama',status(d.status),d.count,d.voidCount,d.cash,d.qris,d.amount,d.cost,d.amount-d.cost,d.countedCash??'',d.difference??'',d.reason,d.revision])]},
 {name:'Rekap Produk',rows:[['Produk','Kategori','Jumlah semua','Hari terjual','Omzet semua','HPP standar semua','Laba kotor semua','Omzet disetujui'],...r.products.map(p=>[p.name,p.category,p.qty,p.days,p.amount,p.cost,p.amount-p.cost,p.approvedAmount])]},
 {name:'Detail Transaksi',rows:[['Nomor','Tanggal','Waktu','Kasir ID','Metode','Status transaksi','Status rekap','Produk','Kategori','Jumlah','Harga satuan','Diskon item','Penjualan bersih','HPP standar','Alasan diskon','Alasan batal','Customer','Tanggal Pesanan'],...r.tickets.flatMap(t=>t.items.map(i=>[t.number,t.date,t.at,t.actor,t.method,t.status,status(r.daily.find(d=>d.date===t.date&&(d.batch||0)===(t.batch||0))?.status),i.name,i.category,i.qty,i.price,i.discount,i.amount,i.hpp,t.discountReason,t.voidReason||'',t.customerName||'',t.orderDate||t.date]))]},
 {name:'Pesanan Belum Dibayar',rows:[['Tanggal Pesanan','Nomor Antrian','Customer','WhatsApp','Status','Total','Sisa','Produk'],...(r.orders||[]).filter(o=>!['Lunas','Batal'].includes(o.status)).map(o=>[o.date,o.queueNumber||'',o.customerName||'',o.phone||'',o.status,o.amount,o.balance,o.items.map(i=>i.name+' × '+i.qty).join('; ')])]},
 {name:'Riwayat Revisi',rows:[['Tanggal','Revisi','Status sebelumnya','Omzet','Alasan revisi','Dibuka oleh','Waktu'],...r.history.map(h=>[h.date,h.revision,status(h.status),h.amount,h.reasonRevision,h.reopenedBy,h.reopenedAt])]}
 ];}
function changeOrder(store,id,d,action,actor){return store.tx(()=>{const old=store.get(id,'posorders');
 if(action==='pay'&&old.status==='Lunas')return store.get(old.ticketId,'postickets');
 if(['Lunas','Batal'].includes(old.status))fail('Pesanan sudah selesai atau dibatalkan.',409);
 if(action==='pay'){
  if(d.expectedAmount!==undefined&&Number(d.expectedAmount)!==old.amount)fail('Total pesanan berubah. Muat ulang antrian sebelum membayar.',409);
  const dt=today(),batch=paymentBatch(store,dt);if(!['Cash','QRIS'].includes(d.method))fail('Pilih Cash atau QRIS untuk pelunasan.');if(d.method==='QRIS'&&d.qrisConfirmed!==true)fail('Konfirmasi pembayaran QRIS terlebih dahulu.');const cash=d.method==='Cash'?money(d.cash):old.amount;if(cash<old.amount)fail('Uang tunai kurang dari total pelunasan.');
  const t=store.put('postickets',{number:'POS-PAY-'+old.id,date:dt,batch,orderDate:old.date,orderId:old.id,queueNumber:old.queueNumber,at:new Date().toISOString(),immediate:store.setting('posImmediatePayments')?.enabled===true,items:old.items,subtotal:old.subtotal,discount:old.discount,discountReason:old.discountReason,amount:old.amount,cost:old.cost,customerName:old.customerName,phone:old.phone,method:d.method,cash,change:cash-old.amount,status:'Selesai',actor,notes:old.notes});store.audit(actor,'pos-sale',t.id);store.put('posorders',{...old,status:'Lunas',balance:0,ticketId:t.id,paidDate:dt,paidAt:t.at},id);store.audit(actor,'edit','posorders:'+id);if(t.immediate)settle(store,t,actor);return t;
 }
 let next={...old};
 if(action==='status'){if(old.orderType!=='queue'||!['Menunggu','Diproses','Siap'].includes(d.status))fail('Status antrian tidak valid.');next.status=d.status;}
 else if(action==='debt'){if(!clean(d.customerName||old.customerName))fail('Nama customer wajib untuk hutang.');next={...next,orderType:'debt',status:'Hutang',method:'Hutang',customerName:clean(d.customerName||old.customerName),phone:clean(d.phone||old.phone)};}
 else if(action==='cancel'){if(!clean(d.reason))fail('Alasan pembatalan wajib diisi.');next.status='Batal';next.balance=0;next.voidReason=clean(d.reason);}
 else if(action==='edit'){
  if(old.orderType!=='queue')fail('Edit rincian hanya untuk antrian.');if(!Array.isArray(d.items)||!d.items.length||d.items.length>100)fail('Isi 1–100 produk.');
  const seen=new Set();next.items=d.items.map(x=>{if(seen.has(x.productId))fail('Produk duplikat.');seen.add(x.productId);const prev=old.items.find(i=>i.productId===x.productId),p=prev||store.get(x.productId,'posproducts');if(!prev&&!p.active)fail('Produk tidak aktif.');const qty=Number(x.qty);if(!Number.isSafeInteger(qty)||qty<1||qty>10000)fail('Jumlah produk harus 1–10.000.');return {productId:x.productId,name:p.name,category:p.category,stockRecipe:p.stockRecipe||[],price:p.price,cost:p.cost,qty,gross:money(p.price*qty)};});
  next.subtotal=money(next.items.reduce((n,i)=>n+i.gross,0));next.discount=money(d.discount||0);next.discountReason=clean(d.discountReason);if(next.discount>next.subtotal||next.discount&&!next.discountReason)fail('Periksa nominal dan alasan diskon.');let sum=0,allocated=0;for(const i of next.items){sum+=i.gross;const n=next.subtotal?Math.round(next.discount*sum/next.subtotal):0;i.discount=n-allocated;allocated=n;i.amount=i.gross-i.discount;i.hpp=money(i.cost*i.qty);}next.amount=next.subtotal-next.discount;if(!next.amount)fail('Total pesanan harus lebih dari nol.');next.balance=next.amount;next.cost=money(next.items.reduce((n,i)=>n+i.hpp,0));next.customerName=clean(d.customerName);next.phone=clean(d.phone);next.notes=clean(d.notes);
 }else fail('Tindakan pesanan tidak valid.');
 const saved=store.put('posorders',next,id);store.audit(actor,action==='cancel'?'pos-void':'edit','posorders:'+id);return saved;
});}
function deleteDay(store,d,user){return store.tx(()=>{if(user.role!=='SUPER ADMIN')fail('Hanya Super Admin dapat menghapus rekap harian.',403);const {dt,batch}=target(d);ensureOpen(store,dt,batch);if(d.confirmDate!==dt||!clean(d.reason))fail('Ketik tanggal yang sama dan isi alasan penghapusan.');const rows=store.list('postickets',{from:dt,to:dt}).filter(t=>(t.batch||0)===batch);for(const t of rows){store.db.prepare('UPDATE records SET deleted=1 WHERE id=?').run(t.id);store.audit(user.id,'delete','postickets:'+t.id);if(t.orderId){const o=store.get(t.orderId,'posorders');store.put('posorders',{...o,status:'Batal',balance:0,voidReason:'Hapus rekap '+dt+': '+clean(d.reason)},o.id);store.audit(user.id,'pos-void','posorders:'+o.id);}}const old=day(store,dt,batch);if(old){store.db.prepare('UPDATE records SET deleted=1 WHERE id=?').run(old.id);store.audit(user.id,'delete','posdays:'+old.id);}store.put('posdeletions',{date:dt,count:rows.length,reason:clean(d.reason),actor:user.id,at:new Date().toISOString()});return {ok:true,count:rows.length};});}
module.exports={saveProduct,createSale,voidSale,changeDay,deleteDay,changeOrder,report,sheets,unit};
