const zlib = require('node:zlib');
const xml = v => String(v ?? '').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const unxml = v => v.replace(/&#(x[0-9a-f]+|\d+);/gi,(_,n)=>String.fromCodePoint(n[0]==='x'?parseInt(n.slice(1),16):Number(n))).replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&amp;/g,'&');
function crc(buf){ let c=0xffffffff; for(const b of buf){ c^=b;for(let i=0;i<8;i++) c=(c>>>1)^((c&1)?0xedb88320:0); } return (c^0xffffffff)>>>0; }
function zip(files){let offset=0;const parts=[],central=[];for(const [name,text] of Object.entries(files)){const n=Buffer.from(name),b=Buffer.from(text),h=Buffer.alloc(30),d=Buffer.alloc(46),sum=crc(b);h.writeUInt32LE(0x04034b50);h.writeUInt16LE(20,4);h.writeUInt32LE(sum,14);h.writeUInt32LE(b.length,18);h.writeUInt32LE(b.length,22);h.writeUInt16LE(n.length,26);d.writeUInt32LE(0x02014b50);d.writeUInt16LE(20,4);d.writeUInt16LE(20,6);d.writeUInt32LE(sum,16);d.writeUInt32LE(b.length,20);d.writeUInt32LE(b.length,24);d.writeUInt16LE(n.length,28);d.writeUInt32LE(offset,42);parts.push(h,n,b);central.push(d,n);offset+=h.length+n.length+b.length;}const cd=Buffer.concat(central),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(Object.keys(files).length,8);end.writeUInt16LE(Object.keys(files).length,10);end.writeUInt32LE(cd.length,12);end.writeUInt32LE(offset,16);return Buffer.concat([...parts,cd,end]);}
function unzip(buf){let e=buf.length-22;while(e>=Math.max(0,buf.length-65557)&&buf.readUInt32LE(e)!==0x06054b50)e--;if(e<0)throw Error('File Excel tidak valid.');let p=buf.readUInt32LE(e+16),size=0;const files={};for(let i=0;i<buf.readUInt16LE(e+10);i++){if(buf.readUInt32LE(p)!==0x02014b50)throw Error('Arsip Excel rusak.');const method=buf.readUInt16LE(p+10),len=buf.readUInt32LE(p+20),expanded=buf.readUInt32LE(p+24),nl=buf.readUInt16LE(p+28),el=buf.readUInt16LE(p+30),cl=buf.readUInt16LE(p+32),at=buf.readUInt32LE(p+42),name=buf.subarray(p+46,p+46+nl).toString();size+=expanded;if(size>20e6)throw Error('Isi Excel terlalu besar.');const start=at+30+buf.readUInt16LE(at+26)+buf.readUInt16LE(at+28),raw=buf.subarray(start,start+len);if(/^(xl\/(worksheets\/sheet1|sharedStrings)\.xml)$/.test(name)){const data=method===0?raw:method===8?zlib.inflateRawSync(raw,{maxOutputLength:20e6}):null;if(!data)throw Error('Kompresi Excel tidak didukung.');files[name]=data.toString();}p+=46+nl+el+cl;}return files;}
function column(n){let s='';do{s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26)-1;}while(n>=0);return s;}
function xlsx(rows){return zip({'[Content_Types].xml':'<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>','_rels/.rels':'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>','xl/workbook.xml':'<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Laporan" sheetId="1" r:id="rId1"/></sheets></workbook>','xl/_rels/workbook.xml.rels':'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>','xl/worksheets/sheet1.xml':`<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>${rows.map((row,i)=>`<row r="${i+1}">${row.map((v,j)=>typeof v==='number'?`<c r="${column(j)}${i+1}"><v>${v}</v></c>`:`<c r="${column(j)}${i+1}" t="inlineStr"><is><t xml:space="preserve">${xml(v)}</t></is></c>`).join('')}</row>`).join('')}</sheetData></worksheet>`});}
function readXlsx(buffer){const f=unzip(buffer),shared=[...(f['xl/sharedStrings.xml']||'').matchAll(/<si\b[^>]*>([\s\S]*?)<\/si>/g)].map(x=>[...x[1].matchAll(/<t\b[^>]*>([\s\S]*?)<\/t>/g)].map(t=>unxml(t[1])).join(''));const sheet=f['xl/worksheets/sheet1.xml'];if(!sheet)throw Error('Sheet pertama tidak ditemukan.');return [...sheet.matchAll(/<row\b[^>]*>([\s\S]*?)<\/row>/g)].map(r=>{const row=[];for(const c of r[1].matchAll(/<c\b([^>]*)>([\s\S]*?)<\/c>/g)){if(/<f\b/.test(c[2]))throw Error('Template import harus berisi nilai, bukan rumus.');const ref=c[1].match(/\br="([A-Z]+)\d+"/),idx=ref?[...ref[1]].reduce((n,ch)=>n*26+ch.charCodeAt(0)-64,0)-1:row.length;const v=c[2].match(/<v\b[^>]*>([\s\S]*?)<\/v>/)?.[1]||'';row[idx]=/\bt="s"/.test(c[1])?shared[Number(v)]:/\bt="inlineStr"/.test(c[1])?[...c[2].matchAll(/<t\b[^>]*>([\s\S]*?)<\/t>/g)].map(x=>unxml(x[1])).join(''):unxml(v);}return row;});}
function readCsv(text){const rows=[];let row=[],v='',q=false;text=text.replace(/^\uFEFF/,'');for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(q&&text[i+1]==='"'){v+='"';i++;}else q=!q;}else if(c===','&&!q){row.push(v);v='';}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&text[i+1]==='\n')i++;row.push(v);if(row.some(Boolean))rows.push(row);row=[];v='';}else v+=c;}if(q)throw Error('Tanda kutip CSV belum ditutup.');row.push(v);if(row.some(Boolean))rows.push(row);return rows;}
function csv(rows){return '\uFEFF'+rows.map(row=>row.map(v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"').join(',')).join('\r\n');}
module.exports={xlsx,readXlsx,readCsv,csv};
function xlsxSheets(sheets){
 const files={'_rels/.rels':'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'};
 files['[Content_Types].xml']='<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>'+sheets.map((s,i)=>'<Override PartName="/xl/worksheets/sheet'+(i+1)+'.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>').join('')+'</Types>';
 files['xl/workbook.xml']='<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>'+sheets.map((s,i)=>'<sheet name="'+xml(s.name)+'" sheetId="'+(i+1)+'" r:id="rId'+(i+1)+'"/>').join('')+'</sheets></workbook>';
 files['xl/_rels/workbook.xml.rels']='<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'+sheets.map((s,i)=>'<Relationship Id="rId'+(i+1)+'" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet'+(i+1)+'.xml"/>').join('')+'</Relationships>';
 sheets.forEach((s,n)=>{files['xl/worksheets/sheet'+(n+1)+'.xml']='<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols><col min="1" max="40" width="22" customWidth="1"/></cols><sheetData>'+s.rows.map((row,i)=>'<row r="'+(i+1)+'">'+row.map((v,j)=>typeof v==='number'?'<c r="'+column(j)+(i+1)+'"><v>'+v+'</v></c>':'<c r="'+column(j)+(i+1)+'" t="inlineStr"><is><t xml:space="preserve">'+xml(v)+'</t></is></c>').join('')+'</row>').join('')+'</sheetData></worksheet>';});return zip(files);
}
module.exports.xlsxSheets=xlsxSheets;
module.exports.zip=zip;
module.exports.xml=xml;
module.exports.column=column;
