const {test,mock}=require('node:test'),assert=require('node:assert/strict');const {Store}=require('../server/store.cjs'),pos=require('../server/pos.cjs'),{createApp}=require('../server/server.cjs');
mock.timers.enable({apis:['Date'],now:Date.parse('2026-09-30T12:00:00Z')});const now=dt=>mock.timers.setTime(Date.parse(dt+'T12:00:00Z')),admin={id:'admin',role:'SUPER ADMIN'};
function setup(){now('2026-09-30');const s=new Store(':memory:');const p=pos.saveProduct(s,{name:'Teh',category:'Tea',price:5000,cost:2000});const body={key:'order-test-00000001',date:'2026-09-30',method:'Cash',cash:10000,items:[{productId:p.id,qty:2}]};return {s,p,body};}
test('hutang lintas bulan masuk rekap hanya saat lunas; retry tidak ganda dan harga pesanan dipertahankan',()=>{const {s,p,body}=setup();try{assert.throws(()=>pos.createSale(s,{...body,method:'Hutang'},'kasir'),/Nama/);const o=pos.createSale(s,{...body,method:'Hutang',customerName:'Ibu Ani'},'kasir');assert.equal(pos.createSale(s,{...body,method:'Hutang',customerName:'Ibu Ani'},'kasir').id,o.id);assert.equal(s.list('postickets').length,0);assert.equal(pos.report(s,'2026-09').amount,0);assert.equal(pos.sheets(pos.report(s,'2026-09')).find(x=>x.name==='Pesanan Belum Dibayar').rows[1][2],'Ibu Ani');pos.saveProduct(s,{...p,price:8000,cost:3000},p.id);now('2026-10-01');assert.throws(()=>pos.changeOrder(s,o.id,{method:'Cash',cash:9999},'pay','kasir'),/kurang/);assert.throws(()=>pos.changeOrder(s,o.id,{method:'QRIS'},'pay','kasir'),/Konfirmasi/);const t=pos.changeOrder(s,o.id,{method:'Cash',cash:20000,expectedAmount:10000},'pay','kasir');assert.equal(t.date,'2026-10-01');assert.equal(t.orderDate,'2026-09-30');assert.equal(t.amount,10000);assert.equal(t.change,10000);assert.equal(pos.changeOrder(s,o.id,{method:'Cash',cash:20000},'pay','kasir').id,t.id);assert.equal(s.list('postickets').length,1);assert.equal(pos.report(s,'2026-09').count,0);assert.equal(pos.report(s,'2026-10').amount,10000);assert.equal(pos.report(s,'2026-10').cost,6000);pos.changeDay(s,{date:t.date,countedCash:10000},'submit',admin);pos.changeDay(s,{date:t.date},'approve',admin);assert.equal(s.report({from:t.date,to:t.date}).revenue,10000);assert.equal(s.report({from:t.date,to:t.date}).cost,6000);assert.equal(s.get(o.id).balance,0);}finally{s.db.close();}});
test('antrian nomor harian, edit, status, hutang, batal serta tanggal tertutup',()=>{const {s,p,body}=setup();try{const o=pos.createSale(s,{...body,mode:'queue',cash:0},'kasir'),b=pos.createSale(s,{...body,key:'order-test-00000002',mode:'queue'},'kasir');assert.equal(o.queueNumber,'A001');assert.equal(b.queueNumber,'A002');assert.equal(pos.report(s,'2026-09').amount,0);pos.changeOrder(s,o.id,{status:'Diproses'},'status','kasir');const edit=pos.changeOrder(s,o.id,{items:[{productId:p.id,qty:3}],customerName:'Budi',discount:1,discountReason:'Promo'},'edit','kasir');assert.equal(edit.amount,14999);assert.equal(edit.items.reduce((n,i)=>n+i.amount,0),14999);assert.throws(()=>pos.changeOrder(s,o.id,{expectedAmount:10000,method:'Cash',cash:20000},'pay','kasir'),/berubah/);pos.changeOrder(s,o.id,{status:'Siap'},'status','kasir');pos.changeOrder(s,o.id,{},'debt','kasir');assert.equal(s.get(o.id).orderType,'debt');assert.throws(()=>pos.changeOrder(s,o.id,{items:[]},'edit','kasir'),/antrian/);pos.changeOrder(s,b.id,{reason:'Batal pesan'},'cancel','kasir');assert.throws(()=>pos.changeOrder(s,b.id,{method:'Cash',cash:10000},'pay','kasir'),/dibatalkan/);s.put('posdays',{date:body.date,status:'Submitted'});assert.equal(pos.changeOrder(s,o.id,{method:'Cash',cash:20000},'pay','kasir').batch,1);assert.equal(s.get(o.id).status,'Lunas');now('2026-10-01');const c=pos.createSale(s,{...body,date:'2026-10-01',key:'order-test-00000003',mode:'queue'},'kasir');assert.equal(c.queueNumber,'A001');}finally{s.db.close();}});
test('hapus rekap hanya super admin, mengarsipkan seluruh rincian dan mencegah retry menghidupkan data',()=>{const {s,body}=setup();try{const t=pos.createSale(s,body,'kasir');assert.throws(()=>pos.deleteDay(s,{date:body.date,confirmDate:body.date,reason:'Uji'}, {role:'ADMIN'}),/Super Admin/);assert.throws(()=>pos.deleteDay(s,{date:body.date,reason:'Uji'},admin),/Ketik/);pos.changeDay(s,{date:body.date,countedCash:10000},'submit',admin);assert.throws(()=>pos.deleteDay(s,{date:body.date,confirmDate:body.date,reason:'Uji'},admin),/revisi/);pos.changeDay(s,{date:body.date},'approve',admin);pos.changeDay(s,{date:body.date,reason:'Koreksi'},'reopen',admin);pos.deleteDay(s,{date:body.date,confirmDate:body.date,reason:'Duplikasi'},admin);assert.equal(s.list('postickets').length,0);assert.equal(s.list('posdays').length,0);assert.equal(s.list('sales').length,0);assert.equal(pos.report(s,'2026-09').details.length,0);assert.equal(s.get(t.id,null,true).deleted,true);assert.throws(()=>pos.createSale(s,body,'kasir'),/dihapus/);assert(s.activityEvents().some(e=>e.recordId===t.id&&e.action==='delete'));}finally{s.db.close();}});
test('API pesanan menjaga izin, nama opsional untuk cash dan server menentukan tanggal pelunasan',async()=>{now('2026-10-01');const {server,store:s}=createApp({dbFile:':memory:'});await new Promise(r=>server.listen(0,'127.0.0.1',r));let cookie='';const call=async(path,method='GET',body)=>{const r=await fetch('http://127.0.0.1:'+server.address().port+path,{method,headers:{Cookie:cookie,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];return {status:r.status,data:await r.json()};};try{await call('/api/setup','POST',{name:'Admin',username:'admin',password:'TestOnly12345'});await call('/api/login','POST',{username:'admin',password:'TestOnly12345'});const p=pos.saveProduct(s,{name:'Teh',category:'Tea',price:5000,cost:2000}),body={key:'api-order-000000001',date:'2026-10-01',method:'Cash',cash:5000,items:[{productId:p.id,qty:1}]};assert.equal((await call('/api/pos/tickets','POST',body)).status,201);const o=await call('/api/pos/tickets','POST',{...body,key:'api-order-000000002',mode:'queue'});assert.equal(o.data.status,'Menunggu');const paid=await call('/api/pos/orders/'+o.data.id+'/pay','POST',{date:'2026-09-01',method:'QRIS',qrisConfirmed:true});assert.equal(paid.data.date,'2026-10-01');await call('/api/users','POST',{name:'Viewer',username:'viewer',password:'TestOnly12345',role:'VIEWER',active:true});await call('/api/login','POST',{username:'viewer',password:'TestOnly12345'});assert.equal((await call('/api/pos/orders/'+o.data.id+'/pay','POST',{method:'Cash',cash:5000})).status,403);assert.equal((await call('/api/pos/day/delete','POST',{date:'2026-10-01',confirmDate:'2026-10-01',reason:'test'})).status,403);}finally{await new Promise(r=>server.close(r));s.db.close();}});

test('rekap tambahan terpisah dari submitted/approved, HPP tidak ganda, revisi dan hapus terisolasi',()=>{const {s,body}=setup();try{
const dt=body.date;pos.createSale(s,body,'kasir');
const queue=pos.createSale(s,{...body,key:'batch-queue-000001',mode:'queue'},'kasir');
const debt=pos.createSale(s,{...body,key:'batch-debt-0000001',method:'Hutang',customerName:'Ani'},'kasir');
const first=pos.changeDay(s,{date:dt,countedCash:10000},'submit',admin);
const paid=pos.changeOrder(s,queue.id,{method:'QRIS',qrisConfirmed:true},'pay','kasir');assert.equal(paid.batch,1);
assert.equal(s.get(first.id).digest,first.digest);assert.equal(s.get(first.id).amount,10000);pos.changeDay(s,{date:dt},'approve',admin);
assert.equal(s.report({from:dt,to:dt}).revenue,10000);assert.equal(s.report({from:dt,to:dt}).cost,4000);
let r=pos.report(s,'2026-09');assert.equal(r.amount,20000);assert.equal(r.approvedAmount,10000);assert.equal(r.details.filter(d=>d.status==='Approved').reduce((n,d)=>n+d.amount,0),10000);
pos.changeDay(s,{date:dt+'~1',countedCash:0},'submit',admin);
const last=pos.changeOrder(s,debt.id,{method:'Cash',cash:10000},'pay','kasir');assert.equal(last.batch,2);
pos.changeDay(s,{date:dt+'~1'},'approve',admin);assert.equal(s.report({from:dt,to:dt}).revenue,20000);assert.equal(s.report({from:dt,to:dt}).cost,8000);
assert.equal(pos.changeOrder(s,debt.id,{method:'Cash',cash:10000},'pay','kasir').id,last.id);assert.equal(s.list('postickets').length,3);
pos.deleteDay(s,{date:dt+'~2',confirmDate:dt,reason:'Uji'},admin);assert.equal(s.list('postickets').length,2);assert.equal(s.report({from:dt,to:dt}).revenue,20000);
pos.changeDay(s,{date:dt+'~1',reason:'Koreksi'},'reopen',admin);assert.equal(s.report({from:dt,to:dt}).revenue,10000);
assert.throws(()=>pos.voidSale(s,s.list('postickets').find(t=>!t.batch).id,'Uji','kasir'),/revisi/);
pos.changeDay(s,{date:dt+'~1',countedCash:0},'submit',admin);pos.changeDay(s,{date:dt+'~1'},'approve',admin);r=pos.report(s,'2026-09');assert.equal(r.approvedAmount,20000);assert.equal(r.final,true);assert.equal(r.products[0].days,1);
}finally{s.db.close();}});
