const {test}=require('node:test'),assert=require('node:assert/strict');
const {Store}=require('../server/store.cjs'),approval=require('../server/report-approvals.cjs'),writer=require('../server/finance-export.cjs');
const {exportSnapshot,restore}=require('../server/snapshot.cjs'),{createApp}=require('../server/server.cjs');
function fixture(){const s=new Store(':memory:'),user=s.saveUser({name:'Owner',username:'owner',password:'Password12345',role:'SUPER ADMIN'},null,'setup'),unit=s.save('units',{name:'Sewa Ruangan'}),customer=s.save('customers',{name:'A',phone:'0812'}),product=s.save('products',{unitId:unit.id,name:'Paket',code:'P',unit:'paket',price:1000000,cost:400000}),invoice=s.save('invoices',{unitId:unit.id,customerId:customer.id,date:'2026-08-01',dueDate:'2026-09-30',eventDate:'2026-09-01',eventStart:'09:00',eventEnd:'12:00',items:[{productId:product.id,name:product.name,unit:'paket',qty:1,price:1000000}]});s.save('payments',{invoiceId:invoice.id,date:'2026-08-01',amount:500000,method:'Cash'});s.save('payments',{invoiceId:invoice.id,date:'2026-09-01',amount:500000,method:'Cash'});return {s,user,unit,customer,product,invoice};}
test('draft HPP otomatis, approval immutable lintas master dan transaksi, snapshot tetap dapat dipulihkan',()=>{const f=fixture(),{s}=f;const period={from:'2026-09-01',to:'2026-09-30'};try{
 assert.equal(s.report(period).cost,200000);s.save('products',{...f.product,cost:0},f.product.id);assert.equal(s.report(period).cost,0);assert.equal(s.get(f.invoice.id,'invoices').total,1000000);
 let preview=approval.prepare(s,period);assert.throws(()=>approval.approve(s,{...period,fingerprint:preview.fingerprint,password:'wrong'},f.user),/Password/);
 s.save('products',{...f.product,cost:600000},f.product.id);assert.throws(()=>approval.approve(s,{...period,fingerprint:preview.fingerprint,password:'Password12345'},f.user),/Data berubah/);
 preview=approval.prepare(s,period);const result=approval.approve(s,{...period,fingerprint:preview.fingerprint,password:'Password12345'},f.user),saved=approval.get(s,result.id);assert.equal(saved.report.cost,300000);const file=writer.workbook(saved.sheets);
 s.save('products',{...f.product,cost:800000,name:'Nama berubah'},f.product.id);s.setSetting('identity',{name:'Nama BUMM berubah'});assert.equal(s.report(period).cost,400000);assert.equal(approval.get(s,result.id).report.cost,300000);assert.deepEqual(writer.workbook(approval.get(s,result.id).sheets),file);
 assert.throws(()=>s.put('reportarchives',{name:'overwritten'},result.id),/immutable/);assert.throws(()=>s.remove('reportarchives',result.id,f.user.id),/immutable/);
 assert.throws(()=>approval.approve(s,{...period,fingerprint:approval.prepare(s,period).fingerprint,password:'Password12345'},f.user),/bertumpang tindih/);
 assert(!JSON.stringify(saved).includes('Password12345'));const recovered=new Store(':memory:');try{restore(recovered,exportSnapshot(s.db));assert.equal(approval.get(recovered,result.id).report.cost,300000);assert.throws(()=>recovered.remove('reportarchives',result.id),/immutable/);}finally{recovered.db.close();}
 }finally{s.db.close();}});
test('master edit hanya setelah izin manual; approval tidak memberi izin',()=>{const {s,user,product}=fixture();try{const admin=s.saveUser({name:'Admin',username:'admin',password:'Password12345',role:'ADMIN'},null,user.id);assert(!s.can(admin,'master','edit'));assert(!s.can(admin,'posmaster','create'));assert(s.can(admin,'master','view'));assert.throws(()=>s.saveUser({...admin,permissions:{...admin.permissions,masterchanges:['edit']}},admin.id,admin.id),/Hanya Super Admin/);const delegated=s.saveUser({...admin,permissions:{...admin.permissions,masterchanges:['edit']}},admin.id,user.id);assert(s.can(delegated,'master','edit'));assert(!s.can(delegated,'master','delete'));assert.throws(()=>approval.approve(s,{from:'2026-09-01',to:'2026-09-30'},delegated),/Super Admin/);}finally{s.db.close();}});
test('API arsip exact periode dan ekspor memakai salinan, role/password dan route edit ditolak',async()=>{
 const {server,store:s}=createApp({dbFile:':memory:'});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;let cookie='';const call=(p,method='GET',body)=>fetch(base+p,{method,headers:{'Content-Type':'application/json',Cookie:cookie},body:body?JSON.stringify(body):undefined});
 try{await call('/api/setup','POST',{name:'Owner',username:'owner',password:'Password12345'});cookie=(await call('/api/login','POST',{username:'owner',password:'Password12345'})).headers.get('set-cookie').split(';')[0];const period={from:'2026-09-01',to:'2026-09-30'},q=new URLSearchParams(period);let preview=await (await call('/api/report-approvals/preview?'+q)).json();assert.equal((await call('/api/report-approvals','POST',{...period,fingerprint:preview.fingerprint,password:'wrong'})).status,403);const response=await call('/api/report-approvals','POST',{...period,fingerprint:preview.fingerprint,password:'Password12345'});assert.equal(response.status,201);const saved=await response.json();assert.equal((await (await call('/api/report?'+q)).json()).approval.id,saved.id);assert.equal((await (await call('/api/dashboard?'+q)).json()).approval.id,saved.id);
 for(const kind of ['profit','revenue','opnamereport']){const a=Buffer.from(await (await call('/api/export?kind='+kind+'&'+q)).arrayBuffer()),b=Buffer.from(await (await call('/api/report-approvals/'+saved.id+'/export?kind='+kind)).arrayBuffer());assert.deepEqual(a,b);assert(a.subarray(0,2).toString()==='PK');}
 assert.equal((await call('/api/records/reportarchives/'+saved.id,'PUT',{from:'2020-01-01'})).status,404);assert.equal((await call('/api/report-approvals/'+saved.id,'DELETE',{})).status,404);
 await call('/api/users','POST',{name:'Admin',username:'admin',password:'Password12345',role:'ADMIN'});cookie=(await call('/api/login','POST',{username:'admin',password:'Password12345'})).headers.get('set-cookie').split(';')[0];assert.equal((await call('/api/report-approvals','POST',{})).status,403);assert.equal((await call('/api/records/units','POST',{name:'Bypass'})).status,403);
 }finally{await new Promise(r=>server.close(r));s.db.close();}
});
test('dua hari tidak membawa invoice/logo seluruh periode; arsip besar tetap satu approval',()=>{const {s,user}=fixture();try{const period={from:'2026-09-01',to:'2026-09-02'};s.put('invoices',{date:'2020-01-01',number:'OLD-LARGE',total:0,identity:{logo:'data:image/png;base64,'+'A'.repeat(2000000)},items:[]});const preview=approval.prepare(s,period);assert(!('invoices'in preview.report));assert(Buffer.byteLength(JSON.stringify(preview))<100000);const original=s.report.bind(s);s.report=f=>({...original(f),warnings:Array.from({length:2400},(_,i)=>({date:period.from,number:'UJI-'+i,message:'Rincian besar '+ 'あ'.repeat(350)}))});const big=approval.prepare(s,period),saved=approval.approve(s,{...period,fingerprint:big.fingerprint,password:'Password12345'},user),manifest=s.get(saved.id,'reportarchives');assert.equal(manifest.storageVersion,2);assert(manifest.parts.length>10);const restored=approval.get(s,saved.id);assert.deepEqual(restored.report.warnings,big.report.warnings);assert.equal(restored.report.revenue,big.report.revenue);assert(writer.workbook(restored.sheets).length>0);assert.throws(()=>s.put('reportarchiveparts',{content:'bad'},manifest.parts[0]),/immutable/);const recovered=new Store(':memory:');try{restore(recovered,exportSnapshot(s.db));assert.deepEqual(approval.get(recovered,saved.id).report.warnings,big.report.warnings);}finally{recovered.db.close();}}finally{s.db.close();}});
test('kegagalan menyimpan potongan membatalkan seluruh approval; arsip lama masih terbaca',()=>{const {s,user}=fixture();try{const old=s.put('reportarchives',{from:'2020-01-01',to:'2020-01-02',report:{revenue:123},sheets:[]});assert.equal(approval.get(s,old.id).report.revenue,123);const period={from:'2026-09-01',to:'2026-09-02'},preview=approval.prepare(s,period),put=s.put.bind(s);s.put=(kind,...args)=>{if(kind==='reportarchives')throw Error('simulated failure');return put(kind,...args);};assert.throws(()=>approval.approve(s,{...period,fingerprint:preview.fingerprint,password:'Password12345'},user),/simulated/);assert.equal(s.list('reportarchiveparts').length,0);assert.equal(approval.list(s).length,1);}finally{s.db.close();}});
